//
//  GeographicalRegionsCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 22/3/26.
//

import Foundation

let geographicalRegions: [GeographicalRegion] = [
    GeographicalRegion(id: 1, name: "North America", countries: [
        Country(id: 1, name: "Canada", regions: [
            
        ]),
        Country(id: 2, name: "United States", regions: [
            
        ]),
        Country(id: 3, name: "Mexico", regions: [
            
        ]),
        Country(id: 4, name: "Belize", regions: [
            
        ]),
    ]),
    
    GeographicalRegion(id: 2, name: "Central America", countries: [
        Country(id: 1, name: "Guatemala", regions: [
            
        ]),
        Country(id: 2, name: "El Salvador", regions: [
            Region(id: 1, name: "Ahuachapán", cities: [
                City(id: 1, name: "Atiquizaya"),
                City(id: 2, name: "El Refugio"),
                City(id: 3, name: "San Lorenzo"),
                City(id: 4, name: "Turín"),
                City(id: 5, name: "Ahuachapán"),
                City(id: 6, name: "Apaneca"),
                City(id: 7, name: "Concepción De Ataco"),
                City(id: 8, name: "Tacuba"),
                City(id: 9, name: "Guaymango"),
                City(id: 10, name: "Jujutla"),
                City(id: 11, name: "San Francisco Menendez"),
                City(id: 12, name: "San Pedro Puxtla"),
            ]),
            Region(id: 2, name: "San Salvador", cities: [
                City(id: 1, name: "Aguilares"),
                City(id: 2, name: "El Paisnal"),
                City(id: 3, name: "Guazapa"),
                City(id: 4, name: "Apopa"),
                City(id: 5, name: "Nejapa"),
                City(id: 6, name: "Llopango"),
                City(id: 7, name: "San Martín"),
                City(id: 8, name: "Soyapango"),
                City(id: 9, name: "Tonacatepeque"),
                City(id: 10, name: "Ayutuxtepeque"),
                City(id: 11, name: "Mejicanos"),
                City(id: 12, name: "San Salvador"),
                City(id: 13, name: "Cuscatancingo"),
                City(id: 14, name: "Ciudad Delgado"),
                City(id: 15, name: "Panchimalco"),
                City(id: 16, name: "Rosario De Mora"),
                City(id: 17, name: "San Marcos"),
                City(id: 18, name: "Santo Tomás"),
                City(id: 19, name: "Santiago Texacuangos"),
            ]),
            Region(id: 3, name: "La Libertad", cities: [
                City(id: 1, name: "Quezaltepeque"),
                City(id: 2, name: "San Matías"),
                City(id: 3, name: "San Pablo Tacachico"),
                City(id: 4, name: "San Juan Opico"),
                City(id: 5, name: "Ciudad Arce"),
                City(id: 6, name: "Colón"),
                City(id: 7, name: "Jayaque"),
                City(id: 8, name: "Sacacoyo"),
                City(id: 9, name: "Tepecoyo"),
                City(id: 10, name: "Talnique"),
                City(id: 11, name: "Antiguo Cuscatlán"),
                City(id: 12, name: "Huizucar"),
                City(id: 13, name: "Nuevo Cuscatlán"),
                City(id: 14, name: "San José Villanueva"),
                City(id: 15, name: "Zaragoza"),
                City(id: 16, name: "Chiltuipán"),
                City(id: 17, name: "Jicalapa"),
                City(id: 18, name: "La Libertad"),
                City(id: 19, name: "Tamanique"),
                City(id: 20, name: "Teotepeque"),
                City(id: 21, name: "Comasagua"),
                City(id: 22, name: "Santa Tecla"),
            ]),
            Region(id: 4, name: "Chalatenango", cities: [
                City(id: 1, name: "La Palma"),
                City(id: 2, name: "Citalá"),
                City(id: 3, name: "San Ignacio"),
                City(id: 4, name: "Nueva Concepción"),
                City(id: 5, name: "Tejutla"),
                City(id: 6, name: "La Reina"),
                City(id: 7, name: "Agua Caliente"),
                City(id: 8, name: "Dulce Nombre De María"),
                City(id: 9, name: "El Paraíso"),
                City(id: 10, name: "San Francisco Morazán"),
                City(id: 11, name: "San Rafael"),
                City(id: 12, name: "Santa Rita"),
                City(id: 13, name: "San Fernando"),
                City(id: 14, name: "Chalatenango"),
                City(id: 15, name: "Arcatao"),
                City(id: 16, name: "Azacualpa"),
                City(id: 17, name: "Comalapa"),
                City(id: 18, name: "Concepción Quezaltepeque"),
                City(id: 19, name: "El Carrizal"),
                City(id: 20, name: "La Laguna"),
                City(id: 21, name: "Las Vueltas"),
                City(id: 22, name: "Nombre De Jesús"),
                City(id: 23, name: "Nueva Trinidad"),
                City(id: 24, name: "Ojos De Agua"),
                City(id: 25, name: "Potonico"),
                City(id: 26, name: "San Antonio De La Cruz"),
                City(id: 27, name: "San Antonio Los Ranchos"),
                City(id: 28, name: "San Francisco Lempa"),
                City(id: 29, name: "San Isidro Labrador"),
                City(id: 30, name: "San José Cancasque"),
                City(id: 31, name: "San Miguel De Mercedes"),
                City(id: 32, name: "San José Las Flores"),
                City(id: 33, name: "San Luis Del Carmen"),
            ]),
            Region(id: 5, name: "Cuscatlán", cities: [
                City(id: 1, name: "Suchitoto"),
                City(id: 2, name: "San José Guayabal"),
                City(id: 3, name: "Oratorio De Concepción"),
                City(id: 4, name: "San Bartolomé Perulapán"),
                City(id: 5, name: "San Pedro Perulapán"),
                City(id: 6, name: "Cojutepeque"),
                City(id: 7, name: "San Rafael Cedros"),
                City(id: 8, name: "Candelaria"),
                City(id: 9, name: "Monte San Juan"),
                City(id: 10, name: "El Carmen"),
                City(id: 11, name: "San Cristóbal"),
                City(id: 12, name: "Santa Cruz Michapa"),
                City(id: 13, name: "San Ramón"),
                City(id: 14, name: "El Rosario"),
                City(id: 15, name: "Santa Cruz Analquito"),
                City(id: 16, name: "Tenancingo"),
            ]),
            Region(id: 6, name: "Cabañas", cities: [
                City(id: 1, name: "Sensuntepeque"),
                City(id: 2, name: "Victoria"),
                City(id: 3, name: "Dolores"),
                City(id: 4, name: "Guacotecti"),
                City(id: 5, name: "San Isidro"),
                City(id: 6, name: "Llobasco"),
                City(id: 7, name: "Tejutepeque"),
                City(id: 8, name: "Jutiapa"),
                City(id: 9, name: "Cinquera"),
            ]),
            Region(id: 7, name: "La Paz", cities: [
                City(id: 1, name: "Cuyultitán"),
                City(id: 2, name: "Olocuilta"),
                City(id: 3, name: "San Juan Talpa"),
                City(id: 4, name: "San Luis Talpa"),
                City(id: 5, name: "San Pedro Masahuat"),
                City(id: 6, name: "Tapalhuaca"),
                City(id: 7, name: "San Francisco Chinameca"),
                City(id: 8, name: "El Rosario"),
                City(id: 9, name: "Jerusalén"),
                City(id: 10, name: "Mercedes La Ceiba"),
                City(id: 11, name: "Paraíso De Osorio"),
                City(id: 12, name: "San Antonio Masahuat"),
                City(id: 13, name: "San Emigdio"),
                City(id: 14, name: "San Juan Tepezontes"),
                City(id: 15, name: "San Luis La Herradura"),
                City(id: 16, name: "San Miguel Tepezontes"),
                City(id: 17, name: "San Pedro Nonualco"),
                City(id: 18, name: "Santa María Ostuma"),
                City(id: 19, name: "Santiago Nonualco"),
                City(id: 20, name: "San Juan Nonualco"),
                City(id: 21, name: "San Rafael Obrajuelo"),
                City(id: 22, name: "Zacatecoluca"),
            ]),
            Region(id: 8, name: "La Unión", cities: [
                City(id: 1, name: "Anamorós"),
                City(id: 2, name: "Bolivar"),
                City(id: 3, name: "Concepción De Oriente"),
                City(id: 4, name: "El Sauce"),
                City(id: 5, name: "Lislique"),
                City(id: 6, name: "Nueva Esparta"),
                City(id: 7, name: "Pasaquina"),
                City(id: 8, name: "Polorós"),
                City(id: 9, name: "San José La Fuente"),
                City(id: 10, name: "Santa Rosa De Lima"),
                City(id: 11, name: "Conchagua"),
                City(id: 12, name: "El Carmen"),
                City(id: 13, name: "Lntipucá"),
                City(id: 14, name: "La Unión"),
                City(id: 15, name: "Meanguera Del Golfo"),
                City(id: 16, name: "San Alejo"),
                City(id: 17, name: "Yayantique"),
                City(id: 18, name: "Yucuaiquín"),
            ]),
            Region(id: 9, name: "Usulután", cities: [
                City(id: 1, name: "Santiago De María"),
                City(id: 2, name: "Alegría"),
                City(id: 3, name: "Berlín"),
                City(id: 4, name: "Mercedes Umana"),
                City(id: 5, name: "Jucuapa"),
                City(id: 6, name: "El Triunfo"),
                City(id: 7, name: "Estanzuelas"),
                City(id: 8, name: "San Buenaventura"),
                City(id: 9, name: "Nueva Granada"),
                City(id: 10, name: "Usulután"),
                City(id: 11, name: "Jucuarán"),
                City(id: 12, name: "San Dionisio"),
                City(id: 13, name: "Concepción Batres"),
                City(id: 14, name: "Santa María"),
                City(id: 15, name: "Ozatlán"),
                City(id: 16, name: "Tecapán"),
                City(id: 17, name: "Santa Elena"),
                City(id: 18, name: "California"),
                City(id: 19, name: "Ereguayquín"),
                City(id: 20, name: "Jiquilisco"),
                City(id: 21, name: "Puerto El Triunfo"),
                City(id: 22, name: "San Agustín"),
                City(id: 23, name: "San Francisco Javier"),
            ]),
            Region(id: 10, name: "Sonsonate", cities: [
                City(id: 1, name: "Juayúa"),
                City(id: 2, name: "Nahuizalco"),
                City(id: 3, name: "Salcoatitán"),
                City(id: 4, name: "Santa Catarina Masahuat"),
                City(id: 5, name: "Sonsonate"),
                City(id: 6, name: "Sonzacate"),
                City(id: 7, name: "Nahulingo"),
                City(id: 8, name: "San Antonio Del Monte"),
                City(id: 9, name: "Santo Domingo De Guzmán"),
                City(id: 10, name: "Lzalco"),
                City(id: 11, name: "Armenia"),
                City(id: 12, name: "Caluco"),
                City(id: 13, name: "San Julián"),
                City(id: 14, name: "Cuisnahuat"),
                City(id: 15, name: "Santa Isabel Lshuatán"),
                City(id: 16, name: "Acajutla"),
            ]),
            Region(id: 11, name: "Santa Ana", cities: [
                City(id: 1, name: "Masahuat"),
                City(id: 2, name: "Metapán"),
                City(id: 3, name: "Santa Rosa Guachipilín"),
                City(id: 4, name: "Texistepeque"),
                City(id: 5, name: "Santa Ana"),
                City(id: 6, name: "Coatepeque"),
                City(id: 7, name: "El Congo"),
                City(id: 8, name: "Candelaria De La Frontera"),
                City(id: 9, name: "Chalchuapa"),
                City(id: 10, name: "El Porvenir"),
                City(id: 11, name: "San Antonio Pajonal"),
                City(id: 12, name: "San Sebastián Salitrillo"),
                City(id: 13, name: "Santiago De La Frontera"),
            ]),
            Region(id: 12, name: "San Vicente", cities: [
                City(id: 1, name: "Apastepeque"),
                City(id: 2, name: "Santa Clara"),
                City(id: 3, name: "San Ildefonso"),
                City(id: 4, name: "San Esteban Catarina"),
                City(id: 5, name: "San Sebastián"),
                City(id: 6, name: "San Lorenzo"),
                City(id: 7, name: "Santo Domingo"),
                City(id: 8, name: "San Vicente"),
                City(id: 9, name: "Guadalupe"),
                City(id: 10, name: "Verapaz"),
                City(id: 11, name: "Tepetitán"),
                City(id: 12, name: "Tecoluca"),
                City(id: 13, name: "San Cayetano Lstepeque"),
            ]),
            Region(id: 13, name: "San Miguel", cities: [
                City(id: 1, name: "Ciudad Barrios"),
                City(id: 2, name: "Sesori"),
                City(id: 3, name: "Nuevo Edén De San Juan"),
                City(id: 4, name: "San Gerardo"),
                City(id: 5, name: "San Luis De La Reina"),
                City(id: 6, name: "Carolina"),
                City(id: 7, name: "San Antonio Del Mosco"),
                City(id: 8, name: "Chapeltique"),
                City(id: 9, name: "San Miguel"),
                City(id: 10, name: "Comacarán"),
                City(id: 11, name: "Uluazapa"),
                City(id: 12, name: "Moncagua"),
                City(id: 13, name: "Quelepa"),
                City(id: 14, name: "Chirilagua"),
                City(id: 15, name: "Chinameca"),
                City(id: 16, name: "Nueva Guadalupe"),
                City(id: 17, name: "Lolotique"),
                City(id: 18, name: "San Jorge"),
                City(id: 19, name: "San Rafael Oriente"),
                City(id: 20, name: "El Tránsito"),
            ]),
            Region(id: 14, name: "Morazán", cities: [
                City(id: 1, name: "Arambala"),
                City(id: 2, name: "Cacaopera"),
                City(id: 3, name: "Corinto"),
                City(id: 4, name: "El Rosario"),
                City(id: 5, name: "Joateca"),
                City(id: 6, name: "Jocoaitique"),
                City(id: 7, name: "Meanguera"),
                City(id: 8, name: "Perquín"),
                City(id: 9, name: "San Fernando"),
                City(id: 10, name: "San Isidro"),
                City(id: 11, name: "Torola"),
                City(id: 12, name: "Chilanga"),
                City(id: 13, name: "Delicias De Concepción"),
                City(id: 14, name: "El Divisadero"),
                City(id: 15, name: "Gualococti"),
                City(id: 16, name: "Guatajiagua"),
                City(id: 17, name: "Jocoro"),
                City(id: 18, name: "Lolotiquillo"),
                City(id: 19, name: "Osicala"),
                City(id: 20, name: "San Carlos"),
                City(id: 21, name: "San Francisco Gotera"),
                City(id: 22, name: "San Simón"),
                City(id: 23, name: "Sensembra"),
                City(id: 24, name: "Sociedad"),
                City(id: 25, name: "Yamabal"),
                City(id: 26, name: "Yoloaiquín"),
            ]),
            
        ]),
        Country(id: 3, name: "Honduras", regions: [
            
        ]),
        Country(id: 4, name: "Nicaragua", regions: [
            
        ]),
        Country(id: 5, name: "Costa Rica", regions: [
            
        ]),
        Country(id: 6, name: "Panama", regions: [
            
        ]),
    ]),
    
    GeographicalRegion(id: 3, name: "Antilles", countries: [
        Country(id: 1, name: "Antigua and Barbuda", regions: []),
        Country(id: 2, name: "Bahamas", regions: []),
        Country(id: 3, name: "Barbados", regions: []),
        Country(id: 4, name: "Cuba", regions: []),
        Country(id: 5, name: "Dominica", regions: []),
        Country(id: 6, name: "Dominican Republic", regions: []),
        Country(id: 7, name: "Grenada", regions: []),
        Country(id: 8, name: "Haiti", regions: []),
        Country(id: 9, name: "Jamaica", regions: []),
        Country(id: 10, name: "Saint Kitts and Nevis", regions: []),
        Country(id: 11, name: "Saint Lucia", regions: []),
        Country(id: 12, name: "Saint Vincent and the Grenadines", regions: []),
        Country(id: 13, name: "Trinidad and Tobago", regions: []),
    ]),
    
    GeographicalRegion(id: 4, name: "South America", countries: [
        Country(id: 1, name: "Argentina", regions: []),
        Country(id: 2, name: "Bolivia", regions: []),
        Country(id: 3, name: "Brazil", regions: []),
        Country(id: 4, name: "Chile", regions: []),
        Country(id: 5, name: "Colombia", regions: []),
        Country(id: 6, name: "Ecuador", regions: []),
        Country(id: 7, name: "Guyana", regions: []),
        Country(id: 8, name: "Paraguay", regions: []),
        Country(id: 9, name: "Peru", regions: []),
        Country(id: 10, name: "Suriname", regions: []),
        Country(id: 11, name: "Uruguay", regions: []),
        Country(id: 12, name: "Venezuela", regions: [])
    ]),
    
    GeographicalRegion(id: 5, name: "Europe", countries: [
        Country(id: 1, name: "France", regions: []),
        Country(id: 2, name: "Germany", regions: []),
        Country(id: 3, name: "Italy", regions: []),
        Country(id: 4, name: "Spain", regions: []),
    ]),
]
