//
//  ElSalvadorCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let elSalvador = Country(id: 2, name: "El Salvador", regions: [
    Region(id: 1, name: "Ahuachapán", cities: [
        City(id: 1, name: "Atiquizaya", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "El Refugio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "San Lorenzo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Turín", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Ahuachapán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Apaneca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Concepción De Ataco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Tacuba", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Guaymango", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Jujutla", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "San Francisco Menendez", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "San Pedro Puxtla", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 2, name: "San Salvador", cities: [
        City(id: 1, name: "Aguilares", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "El Paisnal", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Guazapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Apopa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Nejapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Llopango", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "San Martín", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Soyapango", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Tonacatepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Ayutuxtepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "Mejicanos", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "San Salvador", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "Cuscatancingo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "Ciudad Delgado", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "Panchimalco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "Rosario De Mora", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 17, name: "San Marcos", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 18, name: "Santo Tomás", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 19, name: "Santiago Texacuangos", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 3, name: "La Libertad", cities: [
        City(id: 1, name: "Quezaltepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "San Matías", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "San Pablo Tacachico", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "San Juan Opico", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Ciudad Arce", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Colón", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Jayaque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Sacacoyo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Tepecoyo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Talnique", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "Antiguo Cuscatlán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "Huizucar", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "Nuevo Cuscatlán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "San José Villanueva", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "Zaragoza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "Chiltuipán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 17, name: "Jicalapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 18, name: "La Libertad", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 19, name: "Tamanique", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 20, name: "Teotepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 21, name: "Comasagua", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 22, name: "Santa Tecla", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 4, name: "Chalatenango", cities: [
        City(id: 1, name: "La Palma", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Citalá", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "San Ignacio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Nueva Concepción", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Tejutla", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "La Reina", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Agua Caliente", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Dulce Nombre De María", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "El Paraíso", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "San Francisco Morazán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "San Rafael", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "Santa Rita", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "San Fernando", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "Chalatenango", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "Arcatao", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "Azacualpa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 17, name: "Comalapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 18, name: "Concepción Quezaltepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 19, name: "El Carrizal", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 20, name: "La Laguna", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 21, name: "Las Vueltas", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 22, name: "Nombre De Jesús", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 23, name: "Nueva Trinidad", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 24, name: "Ojos De Agua", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 25, name: "Potonico", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 26, name: "San Antonio De La Cruz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 27, name: "San Antonio Los Ranchos", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 28, name: "San Francisco Lempa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 29, name: "San Isidro Labrador", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 30, name: "San José Cancasque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 31, name: "San Miguel De Mercedes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 32, name: "San José Las Flores", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 33, name: "San Luis Del Carmen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 5, name: "Cuscatlán", cities: [
        City(id: 1, name: "Suchitoto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "San José Guayabal", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Oratorio De Concepción", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "San Bartolomé Perulapán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "San Pedro Perulapán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Cojutepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "San Rafael Cedros", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Candelaria", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Monte San Juan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "El Carmen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "San Cristóbal", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "Santa Cruz Michapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "San Ramón", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "El Rosario", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "Santa Cruz Analquito", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "Tenancingo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 6, name: "Cabañas", cities: [
        City(id: 1, name: "Sensuntepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Victoria", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Dolores", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Guacotecti", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "San Isidro", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Llobasco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Tejutepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Jutiapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Cinquera", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 7, name: "La Paz", cities: [
        City(id: 1, name: "Cuyultitán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Olocuilta", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "San Juan Talpa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "San Luis Talpa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "San Pedro Masahuat", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Tapalhuaca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "San Francisco Chinameca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "El Rosario", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Jerusalén", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Mercedes La Ceiba", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "Paraíso De Osorio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "San Antonio Masahuat", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "San Emigdio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "San Juan Tepezontes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "San Luis La Herradura", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "San Miguel Tepezontes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 17, name: "San Pedro Nonualco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 18, name: "Santa María Ostuma", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 19, name: "Santiago Nonualco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 20, name: "San Juan Nonualco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 21, name: "San Rafael Obrajuelo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 22, name: "Zacatecoluca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 8, name: "La Unión", cities: [
        City(id: 1, name: "Anamorós", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Bolivar", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Concepción De Oriente", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "El Sauce", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Lislique", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Nueva Esparta", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Pasaquina", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Polorós", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "San José La Fuente", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Santa Rosa De Lima", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "Conchagua", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "El Carmen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "Lntipucá", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "La Unión", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "Meanguera Del Golfo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "San Alejo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 17, name: "Yayantique", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 18, name: "Yucuaiquín", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 9, name: "Usulután", cities: [
        City(id: 1, name: "Santiago De María", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Alegría", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Berlín", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Mercedes Umana", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Jucuapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "El Triunfo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Estanzuelas", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "San Buenaventura", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Nueva Granada", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Usulután", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "Jucuarán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "San Dionisio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "Concepción Batres", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "Santa María", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "Ozatlán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "Tecapán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 17, name: "Santa Elena", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 18, name: "California", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 19, name: "Ereguayquín", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 20, name: "Jiquilisco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 21, name: "Puerto El Triunfo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 22, name: "San Agustín", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 23, name: "San Francisco Javier", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 10, name: "Sonsonate", cities: [
        City(id: 1, name: "Juayúa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Nahuizalco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Salcoatitán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Santa Catarina Masahuat", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Sonsonate", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Sonzacate", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Nahulingo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "San Antonio Del Monte", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Santo Domingo De Guzmán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Lzalco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "Armenia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "Caluco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "San Julián", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "Cuisnahuat", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "Santa Isabel Lshuatán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "Acajutla", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 11, name: "Santa Ana", cities: [
        City(id: 1, name: "Masahuat", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Metapán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Santa Rosa Guachipilín", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Texistepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Santa Ana", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Coatepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "El Congo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Candelaria De La Frontera", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Chalchuapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "El Porvenir", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "San Antonio Pajonal", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "San Sebastián Salitrillo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "Santiago De La Frontera", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 12, name: "San Vicente", cities: [
        City(id: 1, name: "Apastepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Santa Clara", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "San Ildefonso", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "San Esteban Catarina", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "San Sebastián", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "San Lorenzo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Santo Domingo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "San Vicente", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Guadalupe", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Verapaz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "Tepetitán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "Tecoluca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "San Cayetano Lstepeque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 13, name: "San Miguel", cities: [
        City(id: 1, name: "Ciudad Barrios", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Sesori", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Nuevo Edén De San Juan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "San Gerardo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "San Luis De La Reina", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Carolina", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "San Antonio Del Mosco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Chapeltique", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "San Miguel", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Comacarán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "Uluazapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "Moncagua", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "Quelepa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "Chirilagua", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "Chinameca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "Nueva Guadalupe", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 17, name: "Lolotique", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 18, name: "San Jorge", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 19, name: "San Rafael Oriente", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 20, name: "El Tránsito", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 14, name: "Morazán", cities: [
        City(id: 1, name: "Arambala", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Cacaopera", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Corinto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "El Rosario", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Joateca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Jocoaitique", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Meanguera", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Perquín", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "San Fernando", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "San Isidro", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 11, name: "Torola", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 12, name: "Chilanga", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 13, name: "Delicias De Concepción", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 14, name: "El Divisadero", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 15, name: "Gualococti", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 16, name: "Guatajiagua", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 17, name: "Jocoro", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 18, name: "Lolotiquillo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 19, name: "Osicala", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 20, name: "San Carlos", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 21, name: "San Francisco Gotera", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 22, name: "San Simón", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 23, name: "Sensembra", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 24, name: "Sociedad", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 25, name: "Yamabal", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 26, name: "Yoloaiquín", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
])
