//
//  FranceCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let france = Country(id: 1, name: "France", regions: [
    Region(id: 1, name: "Île-de-France", cities: [
        City(id: 1, name: "Paris", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Boulogne-Billancourt", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Saint-Denis", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Argenteuil", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Montreuil", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Nanterre", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Vitry-sur-Seine", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Créteil", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Asnières-sur-Seine", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Colombes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 2, name: "Auvergne-Rhône-Alpes", cities: [
        City(id: 1, name: "Lyon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Saint-Étienne", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Grenoble", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Villeurbanne", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Clermont-Ferrand", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Annecy", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Vénissieux", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Valence", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Chambéry", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Vaulx-en-Velin", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 3, name: "Provence-Alpes-Côte d'Azur", cities: [
        City(id: 1, name: "Marseille", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Nice", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Toulon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Aix-en-Provence", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Avignon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Antibes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Cannes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "La Seyne-sur-Mer", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Hyères", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Arles", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 4, name: "Nouvelle-Aquitaine", cities: [
        City(id: 1, name: "Bordeaux", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Limoges", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Poitiers", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Pau", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "La Rochelle", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Mérignac", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Pessac", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Niort", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Bayonne", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Angoulême", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 5, name: "Occitanie", cities: [
        City(id: 1, name: "Toulouse", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Montpellier", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Nîmes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Perpignan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Béziers", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Montauban", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Narbonne", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Albi", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Carcassonne", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Castres", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 6, name: "Grand Est", cities: [
        City(id: 1, name: "Strasbourg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Reims", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Metz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Mulhouse", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Nancy", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Colmar", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Troyes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Charleville-Mézières", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Châlons-en-Champagne", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Thionville", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 7, name: "Hauts-de-France", cities: [
        City(id: 1, name: "Lille", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Amiens", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Roubaix", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Tourcoing", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Dunkerque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Calais", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Villeneuve-d'Ascq", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Saint-Quentin", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Beauvais", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Valenciennes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 8, name: "Normandie", cities: [
        City(id: 1, name: "Le Havre", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Rouen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Caen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Cherbourg-en-Cotentin", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Évreux", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Dieppe", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Saint-Lô", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Lisieux", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Alençon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Louviers", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 9, name: "Bretagne", cities: [
        City(id: 1, name: "Rennes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Brest", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Quimper", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Lorient", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Vannes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Saint-Malo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Saint-Brieuc", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Lanester", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Fougères", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Concarneau", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 10, name: "Pays de la Loire", cities: [
        City(id: 1, name: "Nantes", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Angers", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Le Mans", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Saint-Nazaire", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "La Roche-sur-Yon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Cholet", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Laval", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Rezé", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Saumur", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Herblain", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 11, name: "Bourgogne-Franche-Comté", cities: [
        City(id: 1, name: "Dijon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Besançon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Belfort", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Chalon-sur-Saône", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Nevers", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Auxerre", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Mâcon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Sens", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Montbéliard", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Dole", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 12, name: "Centre-Val de Loire", cities: [
        City(id: 1, name: "Tours", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Orléans", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Bourges", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Blois", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Châteauroux", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Chartres", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Joué-lès-Tours", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Dreux", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Vierzon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Olivet", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 13, name: "Corse", cities: [
        City(id: 1, name: "Ajaccio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Bastia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Porto-Vecchio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Corte", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Borgo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Biguglia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Propriano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Calvi", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Bonifacio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Sartène", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
])
