//
//  FranceCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let france = Country(id: 1, name: "France", regions: [
    Region(id: 1, name: "Île-de-France", cities: [
        City(id: 1, name: "Paris"),
        City(id: 2, name: "Boulogne-Billancourt"),
        City(id: 3, name: "Saint-Denis"),
        City(id: 4, name: "Argenteuil"),
        City(id: 5, name: "Montreuil"),
        City(id: 6, name: "Nanterre"),
        City(id: 7, name: "Vitry-sur-Seine"),
        City(id: 8, name: "Créteil"),
        City(id: 9, name: "Asnières-sur-Seine"),
        City(id: 10, name: "Colombes"),
    ]),
    Region(id: 2, name: "Auvergne-Rhône-Alpes", cities: [
        City(id: 1, name: "Lyon"),
        City(id: 2, name: "Saint-Étienne"),
        City(id: 3, name: "Grenoble"),
        City(id: 4, name: "Villeurbanne"),
        City(id: 5, name: "Clermont-Ferrand"),
        City(id: 6, name: "Annecy"),
        City(id: 7, name: "Vénissieux"),
        City(id: 8, name: "Valence"),
        City(id: 9, name: "Chambéry"),
        City(id: 10, name: "Vaulx-en-Velin"),
    ]),
    Region(id: 3, name: "Provence-Alpes-Côte d'Azur", cities: [
        City(id: 1, name: "Marseille"),
        City(id: 2, name: "Nice"),
        City(id: 3, name: "Toulon"),
        City(id: 4, name: "Aix-en-Provence"),
        City(id: 5, name: "Avignon"),
        City(id: 6, name: "Antibes"),
        City(id: 7, name: "Cannes"),
        City(id: 8, name: "La Seyne-sur-Mer"),
        City(id: 9, name: "Hyères"),
        City(id: 10, name: "Arles"),
    ]),
    Region(id: 4, name: "Nouvelle-Aquitaine", cities: [
        City(id: 1, name: "Bordeaux"),
        City(id: 2, name: "Limoges"),
        City(id: 3, name: "Poitiers"),
        City(id: 4, name: "Pau"),
        City(id: 5, name: "La Rochelle"),
        City(id: 6, name: "Mérignac"),
        City(id: 7, name: "Pessac"),
        City(id: 8, name: "Niort"),
        City(id: 9, name: "Bayonne"),
        City(id: 10, name: "Angoulême"),
    ]),
    Region(id: 5, name: "Occitanie", cities: [
        City(id: 1, name: "Toulouse"),
        City(id: 2, name: "Montpellier"),
        City(id: 3, name: "Nîmes"),
        City(id: 4, name: "Perpignan"),
        City(id: 5, name: "Béziers"),
        City(id: 6, name: "Montauban"),
        City(id: 7, name: "Narbonne"),
        City(id: 8, name: "Albi"),
        City(id: 9, name: "Carcassonne"),
        City(id: 10, name: "Castres"),
    ]),
    Region(id: 6, name: "Grand Est", cities: [
        City(id: 1, name: "Strasbourg"),
        City(id: 2, name: "Reims"),
        City(id: 3, name: "Metz"),
        City(id: 4, name: "Mulhouse"),
        City(id: 5, name: "Nancy"),
        City(id: 6, name: "Colmar"),
        City(id: 7, name: "Troyes"),
        City(id: 8, name: "Charleville-Mézières"),
        City(id: 9, name: "Châlons-en-Champagne"),
        City(id: 10, name: "Thionville"),
    ]),
    Region(id: 7, name: "Hauts-de-France", cities: [
        City(id: 1, name: "Lille"),
        City(id: 2, name: "Amiens"),
        City(id: 3, name: "Roubaix"),
        City(id: 4, name: "Tourcoing"),
        City(id: 5, name: "Dunkerque"),
        City(id: 6, name: "Calais"),
        City(id: 7, name: "Villeneuve-d'Ascq"),
        City(id: 8, name: "Saint-Quentin"),
        City(id: 9, name: "Beauvais"),
        City(id: 10, name: "Valenciennes"),
    ]),
    Region(id: 8, name: "Normandie", cities: [
        City(id: 1, name: "Le Havre"),
        City(id: 2, name: "Rouen"),
        City(id: 3, name: "Caen"),
        City(id: 4, name: "Cherbourg-en-Cotentin"),
        City(id: 5, name: "Évreux"),
        City(id: 6, name: "Dieppe"),
        City(id: 7, name: "Saint-Lô"),
        City(id: 8, name: "Lisieux"),
        City(id: 9, name: "Alençon"),
        City(id: 10, name: "Louviers"),
    ]),
    Region(id: 9, name: "Bretagne", cities: [
        City(id: 1, name: "Rennes"),
        City(id: 2, name: "Brest"),
        City(id: 3, name: "Quimper"),
        City(id: 4, name: "Lorient"),
        City(id: 5, name: "Vannes"),
        City(id: 6, name: "Saint-Malo"),
        City(id: 7, name: "Saint-Brieuc"),
        City(id: 8, name: "Lanester"),
        City(id: 9, name: "Fougères"),
        City(id: 10, name: "Concarneau"),
    ]),
    Region(id: 10, name: "Pays de la Loire", cities: [
        City(id: 1, name: "Nantes"),
        City(id: 2, name: "Angers"),
        City(id: 3, name: "Le Mans"),
        City(id: 4, name: "Saint-Nazaire"),
        City(id: 5, name: "La Roche-sur-Yon"),
        City(id: 6, name: "Cholet"),
        City(id: 7, name: "Laval"),
        City(id: 8, name: "Rezé"),
        City(id: 9, name: "Saumur"),
        City(id: 10, name: "Herblain"),
    ]),
    Region(id: 11, name: "Bourgogne-Franche-Comté", cities: [
        City(id: 1, name: "Dijon"),
        City(id: 2, name: "Besançon"),
        City(id: 3, name: "Belfort"),
        City(id: 4, name: "Chalon-sur-Saône"),
        City(id: 5, name: "Nevers"),
        City(id: 6, name: "Auxerre"),
        City(id: 7, name: "Mâcon"),
        City(id: 8, name: "Sens"),
        City(id: 9, name: "Montbéliard"),
        City(id: 10, name: "Dole"),
    ]),
    Region(id: 12, name: "Centre-Val de Loire", cities: [
        City(id: 1, name: "Tours"),
        City(id: 2, name: "Orléans"),
        City(id: 3, name: "Bourges"),
        City(id: 4, name: "Blois"),
        City(id: 5, name: "Châteauroux"),
        City(id: 6, name: "Chartres"),
        City(id: 7, name: "Joué-lès-Tours"),
        City(id: 8, name: "Dreux"),
        City(id: 9, name: "Vierzon"),
        City(id: 10, name: "Olivet"),
    ]),
    Region(id: 13, name: "Corse", cities: [
        City(id: 1, name: "Ajaccio"),
        City(id: 2, name: "Bastia"),
        City(id: 3, name: "Porto-Vecchio"),
        City(id: 4, name: "Corte"),
        City(id: 5, name: "Borgo"),
        City(id: 6, name: "Biguglia"),
        City(id: 7, name: "Propriano"),
        City(id: 8, name: "Calvi"),
        City(id: 9, name: "Bonifacio"),
        City(id: 10, name: "Sartène"),
    ]),
])
