//
//  GermanyCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let germany = Country(id: 2, name: "Germany", regions: [
    Region(id: 1, name: "Baden-Württemberg", cities: [
        City(id: 1, name: "Stuttgart", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Karlsruhe", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Mannheim", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Freiburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Heidelberg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Ulm", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Heilbronn", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Pforzheim", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Reutlingen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Ludwigsburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 2, name: "Bavaria", cities: [
        City(id: 1, name: "Munich", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Nuremberg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Augsburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Regensburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Ingolstadt", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Würzburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Fürth", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Erlangen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Bamberg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Bayreuth", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 3, name: "Berlin", cities: [
        City(id: 1, name: "Berlin", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 4, name: "Brandenburg", cities: [
        City(id: 1, name: "Potsdam", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Cottbus", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Brandenburg an der Havel", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Frankfurt (Oder)", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Oranienburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Falkensee", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Eberswalde", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Bernau bei Berlin", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Königs Wusterhausen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Schwedt/Oder", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 5, name: "Bremen", cities: [
        City(id: 1, name: "Bremen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Bremerhaven", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 6, name: "Hamburg", cities: [
        City(id: 1, name: "Hamburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 7, name: "Hesse", cities: [
        City(id: 1, name: "Frankfurt am Main", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Wiesbaden", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Kassel", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Darmstadt", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Offenbach am Main", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Hanau", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Gießen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Marburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Fulda", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Wetzlar", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 8, name: "Lower Saxony", cities: [
        City(id: 1, name: "Hanover", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Braunschweig", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Oldenburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Osnabrück", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Wolfsburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Göttingen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Hildesheim", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Salzgitter", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Wilhelmshaven", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Delmenhorst", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 9, name: "Mecklenburg-Vorpommern", cities: [
        City(id: 1, name: "Rostock", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Schwerin", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Neubrandenburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Stralsund", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Greifswald", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Wismar", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Güstrow", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Waren (Müritz)", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Neustrelitz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Parchim", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 10, name: "North Rhine-Westphalia", cities: [
        City(id: 1, name: "Cologne", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Düsseldorf", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Dortmund", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Essen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Duisburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Bochum", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Wuppertal", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Bielefeld", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Bonn", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Münster", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 11, name: "Rhineland-Palatinate", cities: [
        City(id: 1, name: "Mainz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Ludwigshafen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Koblenz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Trier", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Kaiserslautern", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Worms", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Neuwied", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Neustadt an der Weinstraße", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Speyer", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Bad Kreuznach", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 12, name: "Saarland", cities: [
        City(id: 1, name: "Saarbrücken", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Neunkirchen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Homburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Völklingen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Sankt Ingbert", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Saarlouis", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Merzig", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "St. Wendel", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Blieskastel", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Dillingen/Saar", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 13, name: "Saxony", cities: [
        City(id: 1, name: "Leipzig", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Dresden", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Chemnitz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Zwickau", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Plauen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Görlitz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Bautzen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Freiberg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Hoyerswerda", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Pirna", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 14, name: "Saxony-Anhalt", cities: [
        City(id: 1, name: "Halle (Saale)", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Magdeburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Dessau-Roßlau", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Lutherstadt Wittenberg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Halberstadt", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Stendal", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Bitterfeld-Wolfen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Weißenfels", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Merseburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Bernburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 15, name: "Schleswig-Holstein", cities: [
        City(id: 1, name: "Kiel", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Lübeck", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Flensburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Neumünster", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Norderstedt", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Elmshorn", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Pinneberg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Itzehoe", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Wedel", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Ahrensburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 16, name: "Thuringia", cities: [
        City(id: 1, name: "Erfurt", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Jena", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Gera", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Weimar", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Gotha", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Eisenach", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Nordhausen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Suhl", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Mühlhausen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Altenburg", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
])
