//
//  GermanyCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let germany = Country(id: 2, name: "Germany", regions: [
    Region(id: 1, name: "Baden-Württemberg", cities: [
        City(id: 1, name: "Stuttgart"),
        City(id: 2, name: "Karlsruhe"),
        City(id: 3, name: "Mannheim"),
        City(id: 4, name: "Freiburg"),
        City(id: 5, name: "Heidelberg"),
        City(id: 6, name: "Ulm"),
        City(id: 7, name: "Heilbronn"),
        City(id: 8, name: "Pforzheim"),
        City(id: 9, name: "Reutlingen"),
        City(id: 10, name: "Ludwigsburg"),
    ]),
    Region(id: 2, name: "Bavaria", cities: [
        City(id: 1, name: "Munich"),
        City(id: 2, name: "Nuremberg"),
        City(id: 3, name: "Augsburg"),
        City(id: 4, name: "Regensburg"),
        City(id: 5, name: "Ingolstadt"),
        City(id: 6, name: "Würzburg"),
        City(id: 7, name: "Fürth"),
        City(id: 8, name: "Erlangen"),
        City(id: 9, name: "Bamberg"),
        City(id: 10, name: "Bayreuth"),
    ]),
    Region(id: 3, name: "Berlin", cities: [
        City(id: 1, name: "Berlin"),
    ]),
    Region(id: 4, name: "Brandenburg", cities: [
        City(id: 1, name: "Potsdam"),
        City(id: 2, name: "Cottbus"),
        City(id: 3, name: "Brandenburg an der Havel"),
        City(id: 4, name: "Frankfurt (Oder)"),
        City(id: 5, name: "Oranienburg"),
        City(id: 6, name: "Falkensee"),
        City(id: 7, name: "Eberswalde"),
        City(id: 8, name: "Bernau bei Berlin"),
        City(id: 9, name: "Königs Wusterhausen"),
        City(id: 10, name: "Schwedt/Oder"),
    ]),
    Region(id: 5, name: "Bremen", cities: [
        City(id: 1, name: "Bremen"),
        City(id: 2, name: "Bremerhaven"),
    ]),
    Region(id: 6, name: "Hamburg", cities: [
        City(id: 1, name: "Hamburg"),
    ]),
    Region(id: 7, name: "Hesse", cities: [
        City(id: 1, name: "Frankfurt am Main"),
        City(id: 2, name: "Wiesbaden"),
        City(id: 3, name: "Kassel"),
        City(id: 4, name: "Darmstadt"),
        City(id: 5, name: "Offenbach am Main"),
        City(id: 6, name: "Hanau"),
        City(id: 7, name: "Gießen"),
        City(id: 8, name: "Marburg"),
        City(id: 9, name: "Fulda"),
        City(id: 10, name: "Wetzlar"),
    ]),
    Region(id: 8, name: "Lower Saxony", cities: [
        City(id: 1, name: "Hanover"),
        City(id: 2, name: "Braunschweig"),
        City(id: 3, name: "Oldenburg"),
        City(id: 4, name: "Osnabrück"),
        City(id: 5, name: "Wolfsburg"),
        City(id: 6, name: "Göttingen"),
        City(id: 7, name: "Hildesheim"),
        City(id: 8, name: "Salzgitter"),
        City(id: 9, name: "Wilhelmshaven"),
        City(id: 10, name: "Delmenhorst"),
    ]),
    Region(id: 9, name: "Mecklenburg-Vorpommern", cities: [
        City(id: 1, name: "Rostock"),
        City(id: 2, name: "Schwerin"),
        City(id: 3, name: "Neubrandenburg"),
        City(id: 4, name: "Stralsund"),
        City(id: 5, name: "Greifswald"),
        City(id: 6, name: "Wismar"),
        City(id: 7, name: "Güstrow"),
        City(id: 8, name: "Waren (Müritz)"),
        City(id: 9, name: "Neustrelitz"),
        City(id: 10, name: "Parchim"),
    ]),
    Region(id: 10, name: "North Rhine-Westphalia", cities: [
        City(id: 1, name: "Cologne"),
        City(id: 2, name: "Düsseldorf"),
        City(id: 3, name: "Dortmund"),
        City(id: 4, name: "Essen"),
        City(id: 5, name: "Duisburg"),
        City(id: 6, name: "Bochum"),
        City(id: 7, name: "Wuppertal"),
        City(id: 8, name: "Bielefeld"),
        City(id: 9, name: "Bonn"),
        City(id: 10, name: "Münster"),
    ]),
    Region(id: 11, name: "Rhineland-Palatinate", cities: [
        City(id: 1, name: "Mainz"),
        City(id: 2, name: "Ludwigshafen"),
        City(id: 3, name: "Koblenz"),
        City(id: 4, name: "Trier"),
        City(id: 5, name: "Kaiserslautern"),
        City(id: 6, name: "Worms"),
        City(id: 7, name: "Neuwied"),
        City(id: 8, name: "Neustadt an der Weinstraße"),
        City(id: 9, name: "Speyer"),
        City(id: 10, name: "Bad Kreuznach"),
    ]),
    Region(id: 12, name: "Saarland", cities: [
        City(id: 1, name: "Saarbrücken"),
        City(id: 2, name: "Neunkirchen"),
        City(id: 3, name: "Homburg"),
        City(id: 4, name: "Völklingen"),
        City(id: 5, name: "Sankt Ingbert"),
        City(id: 6, name: "Saarlouis"),
        City(id: 7, name: "Merzig"),
        City(id: 8, name: "St. Wendel"),
        City(id: 9, name: "Blieskastel"),
        City(id: 10, name: "Dillingen/Saar"),
    ]),
    Region(id: 13, name: "Saxony", cities: [
        City(id: 1, name: "Leipzig"),
        City(id: 2, name: "Dresden"),
        City(id: 3, name: "Chemnitz"),
        City(id: 4, name: "Zwickau"),
        City(id: 5, name: "Plauen"),
        City(id: 6, name: "Görlitz"),
        City(id: 7, name: "Bautzen"),
        City(id: 8, name: "Freiberg"),
        City(id: 9, name: "Hoyerswerda"),
        City(id: 10, name: "Pirna"),
    ]),
    Region(id: 14, name: "Saxony-Anhalt", cities: [
        City(id: 1, name: "Halle (Saale)"),
        City(id: 2, name: "Magdeburg"),
        City(id: 3, name: "Dessau-Roßlau"),
        City(id: 4, name: "Lutherstadt Wittenberg"),
        City(id: 5, name: "Halberstadt"),
        City(id: 6, name: "Stendal"),
        City(id: 7, name: "Bitterfeld-Wolfen"),
        City(id: 8, name: "Weißenfels"),
        City(id: 9, name: "Merseburg"),
        City(id: 10, name: "Bernburg"),
    ]),
    Region(id: 15, name: "Schleswig-Holstein", cities: [
        City(id: 1, name: "Kiel"),
        City(id: 2, name: "Lübeck"),
        City(id: 3, name: "Flensburg"),
        City(id: 4, name: "Neumünster"),
        City(id: 5, name: "Norderstedt"),
        City(id: 6, name: "Elmshorn"),
        City(id: 7, name: "Pinneberg"),
        City(id: 8, name: "Itzehoe"),
        City(id: 9, name: "Wedel"),
        City(id: 10, name: "Ahrensburg"),
    ]),
    Region(id: 16, name: "Thuringia", cities: [
        City(id: 1, name: "Erfurt"),
        City(id: 2, name: "Jena"),
        City(id: 3, name: "Gera"),
        City(id: 4, name: "Weimar"),
        City(id: 5, name: "Gotha"),
        City(id: 6, name: "Eisenach"),
        City(id: 7, name: "Nordhausen"),
        City(id: 8, name: "Suhl"),
        City(id: 9, name: "Mühlhausen"),
        City(id: 10, name: "Altenburg"),
    ]),
])
