//
//  ItalyCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let italy = Country(id: 3, name: "Italy", regions: [
    Region(id: 1, name: "Abruzzo", cities: [
        City(id: 1, name: "L'Aquila"),
        City(id: 2, name: "Pescara"),
        City(id: 3, name: "Teramo"),
        City(id: 4, name: "Chieti"),
        City(id: 5, name: "Montesilvano"),
        City(id: 6, name: "Vasto"),
        City(id: 7, name: "Avezzano"),
        City(id: 8, name: "Lanciano"),
        City(id: 9, name: "Sulmona"),
        City(id: 10, name: "Francavilla al Mare"),
    ]),
    Region(id: 2, name: "Basilicata", cities: [
        City(id: 1, name: "Potenza"),
        City(id: 2, name: "Matera"),
        City(id: 3, name: "Policoro"),
        City(id: 4, name: "Melfi"),
        City(id: 5, name: "Pisticci"),
        City(id: 6, name: "Lavello"),
        City(id: 7, name: "Rionero in Vulture"),
        City(id: 8, name: "Lauria"),
        City(id: 9, name: "Bernalda"),
        City(id: 10, name: "Venosa"),
    ]),
    Region(id: 3, name: "Calabria", cities: [
        City(id: 1, name: "Catanzaro"),
        City(id: 2, name: "Reggio Calabria"),
        City(id: 3, name: "Cosenza"),
        City(id: 4, name: "Lamezia Terme"),
        City(id: 5, name: "Crotone"),
        City(id: 6, name: "Vibo Valentia"),
        City(id: 7, name: "Castrovillari"),
        City(id: 8, name: "Acri"),
        City(id: 9, name: "Rossano"),
        City(id: 10, name: "Corigliano Calabro"),
    ]),
    Region(id: 4, name: "Campania", cities: [
        City(id: 1, name: "Naples"),
        City(id: 2, name: "Salerno"),
        City(id: 3, name: "Giugliano in Campania"),
        City(id: 4, name: "Torre del Greco"),
        City(id: 5, name: "Pozzuoli"),
        City(id: 6, name: "Caserta"),
        City(id: 7, name: "Benevento"),
        City(id: 8, name: "Avellino"),
        City(id: 9, name: "Castellammare di Stabia"),
        City(id: 10, name: "Afragola"),
    ]),
    Region(id: 5, name: "Emilia-Romagna", cities: [
        City(id: 1, name: "Bologna"),
        City(id: 2, name: "Parma"),
        City(id: 3, name: "Modena"),
        City(id: 4, name: "Reggio Emilia"),
        City(id: 5, name: "Ravenna"),
        City(id: 6, name: "Rimini"),
        City(id: 7, name: "Ferrara"),
        City(id: 8, name: "Forlì"),
        City(id: 9, name: "Piacenza"),
        City(id: 10, name: "Cesena"),
    ]),
    Region(id: 6, name: "Friuli-Venezia Giulia", cities: [
        City(id: 1, name: "Trieste"),
        City(id: 2, name: "Udine"),
        City(id: 3, name: "Pordenone"),
        City(id: 4, name: "Gorizia"),
        City(id: 5, name: "Monfalcone"),
        City(id: 6, name: "Sacile"),
        City(id: 7, name: "Cordenons"),
        City(id: 8, name: "Codroipo"),
        City(id: 9, name: "Azzano Decimo"),
        City(id: 10, name: "San Vito al Tagliamento"),
    ]),
    Region(id: 7, name: "Lazio", cities: [
        City(id: 1, name: "Rome"),
        City(id: 2, name: "Latina"),
        City(id: 3, name: "Guidonia Montecelio"),
        City(id: 4, name: "Fiumicino"),
        City(id: 5, name: "Aprilia"),
        City(id: 6, name: "Viterbo"),
        City(id: 7, name: "Pomezia"),
        City(id: 8, name: "Tivoli"),
        City(id: 9, name: "Anzio"),
        City(id: 10, name: "Velletri"),
    ]),
    Region(id: 8, name: "Liguria", cities: [
        City(id: 1, name: "Genoa"),
        City(id: 2, name: "La Spezia"),
        City(id: 3, name: "Savona"),
        City(id: 4, name: "Sanremo"),
        City(id: 5, name: "Imperia"),
        City(id: 6, name: "Rapallo"),
        City(id: 7, name: "Chiavari"),
        City(id: 8, name: "Ventimiglia"),
        City(id: 9, name: "Albenga"),
        City(id: 10, name: "Sarzana"),
    ]),
    Region(id: 9, name: "Lombardy", cities: [
        City(id: 1, name: "Milan"),
        City(id: 2, name: "Brescia"),
        City(id: 3, name: "Monza"),
        City(id: 4, name: "Bergamo"),
        City(id: 5, name: "Busto Arsizio"),
        City(id: 6, name: "Como"),
        City(id: 7, name: "Varese"),
        City(id: 8, name: "Sesto San Giovanni"),
        City(id: 9, name: "Cinisello Balsamo"),
        City(id: 10, name: "Pavia"),
    ]),
    Region(id: 10, name: "Marche", cities: [
        City(id: 1, name: "Ancona"),
        City(id: 2, name: "Pesaro"),
        City(id: 3, name: "Fano"),
        City(id: 4, name: "Ascoli Piceno"),
        City(id: 5, name: "San Benedetto del Tronto"),
        City(id: 6, name: "Senigallia"),
        City(id: 7, name: "Macerata"),
        City(id: 8, name: "Civitanova Marche"),
        City(id: 9, name: "Jesi"),
        City(id: 10, name: "Fermo"),
    ]),
    Region(id: 11, name: "Molise", cities: [
        City(id: 1, name: "Campobasso"),
        City(id: 2, name: "Isernia"),
        City(id: 3, name: "Termoli"),
        City(id: 4, name: "Venafro"),
        City(id: 5, name: "Bojano"),
        City(id: 6, name: "Campomarino"),
        City(id: 7, name: "Larino"),
        City(id: 8, name: "Montenero di Bisaccia"),
        City(id: 9, name: "Riccia"),
        City(id: 10, name: "Agnone"),
    ]),
    Region(id: 12, name: "Piedmont", cities: [
        City(id: 1, name: "Turin"),
        City(id: 2, name: "Novara"),
        City(id: 3, name: "Alessandria"),
        City(id: 4, name: "Asti"),
        City(id: 5, name: "Moncalieri"),
        City(id: 6, name: "Cuneo"),
        City(id: 7, name: "Collegno"),
        City(id: 8, name: "Rivoli"),
        City(id: 9, name: "Vercelli"),
        City(id: 10, name: "Biella"),
    ]),
    Region(id: 13, name: "Apulia", cities: [
        City(id: 1, name: "Bari"),
        City(id: 2, name: "Taranto"),
        City(id: 3, name: "Foggia"),
        City(id: 4, name: "Andria"),
        City(id: 5, name: "Barletta"),
        City(id: 6, name: "Lecce"),
        City(id: 7, name: "Brindisi"),
        City(id: 8, name: "Altamura"),
        City(id: 9, name: "Molfetta"),
        City(id: 10, name: "Cerignola"),
    ]),
    Region(id: 14, name: "Sardinia", cities: [
        City(id: 1, name: "Cagliari"),
        City(id: 2, name: "Sassari"),
        City(id: 3, name: "Quartu Sant'Elena"),
        City(id: 4, name: "Olbia"),
        City(id: 5, name: "Alghero"),
        City(id: 6, name: "Nuoro"),
        City(id: 7, name: "Oristano"),
        City(id: 8, name: "Selargius"),
        City(id: 9, name: "Carbonia"),
        City(id: 10, name: "Iglesias"),
    ]),
    Region(id: 15, name: "Sicily", cities: [
        City(id: 1, name: "Palermo"),
        City(id: 2, name: "Catania"),
        City(id: 3, name: "Messina"),
        City(id: 4, name: "Syracuse"),
        City(id: 5, name: "Marsala"),
        City(id: 6, name: "Gela"),
        City(id: 7, name: "Ragusa"),
        City(id: 8, name: "Trapani"),
        City(id: 9, name: "Caltanissetta"),
        City(id: 10, name: "Vittoria"),
    ]),
    Region(id: 16, name: "Tuscany", cities: [
        City(id: 1, name: "Florence"),
        City(id: 2, name: "Prato"),
        City(id: 3, name: "Livorno"),
        City(id: 4, name: "Arezzo"),
        City(id: 5, name: "Pistoia"),
        City(id: 6, name: "Pisa"),
        City(id: 7, name: "Lucca"),
        City(id: 8, name: "Grosseto"),
        City(id: 9, name: "Massa"),
        City(id: 10, name: "Carrara"),
    ]),
    Region(id: 17, name: "Trentino-Alto Adige", cities: [
        City(id: 1, name: "Trento"),
        City(id: 2, name: "Bolzano"),
        City(id: 3, name: "Rovereto"),
        City(id: 4, name: "Merano"),
        City(id: 5, name: "Brixen"),
        City(id: 6, name: "Pergine Valsugana"),
        City(id: 7, name: "Laives"),
        City(id: 8, name: "Arco"),
        City(id: 9, name: "Riva del Garda"),
        City(id: 10, name: "Brunico"),
    ]),
    Region(id: 18, name: "Umbria", cities: [
        City(id: 1, name: "Perugia"),
        City(id: 2, name: "Terni"),
        City(id: 3, name: "Foligno"),
        City(id: 4, name: "Città di Castello"),
        City(id: 5, name: "Spoleto"),
        City(id: 6, name: "Gubbio"),
        City(id: 7, name: "Assisi"),
        City(id: 8, name: "Bastia Umbra"),
        City(id: 9, name: "Orvieto"),
        City(id: 10, name: "Corciano"),
    ]),
    Region(id: 19, name: "Valle d'Aosta", cities: [
        City(id: 1, name: "Aosta"),
        City(id: 2, name: "Sarre"),
        City(id: 3, name: "Châtillon"),
        City(id: 4, name: "Saint-Vincent"),
        City(id: 5, name: "Quart"),
        City(id: 6, name: "Pont-Saint-Martin"),
        City(id: 7, name: "Saint-Christophe"),
        City(id: 8, name: "Gressan"),
        City(id: 9, name: "Courmayeur"),
        City(id: 10, name: "Verrès"),
    ]),
    Region(id: 20, name: "Veneto", cities: [
        City(id: 1, name: "Venice"),
        City(id: 2, name: "Verona"),
        City(id: 3, name: "Padua"),
        City(id: 4, name: "Vicenza"),
        City(id: 5, name: "Treviso"),
        City(id: 6, name: "Rovigo"),
        City(id: 7, name: "Chioggia"),
        City(id: 8, name: "Bassano del Grappa"),
        City(id: 9, name: "San Donà di Piave"),
        City(id: 10, name: "Schio"),
    ]),
])
