//
//  ItalyCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let italy = Country(id: 3, name: "Italy", regions: [
    Region(id: 1, name: "Abruzzo", cities: [
        City(id: 1, name: "L'Aquila", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Pescara", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Teramo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Chieti", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Montesilvano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Vasto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Avezzano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Lanciano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Sulmona", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Francavilla al Mare", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 2, name: "Basilicata", cities: [
        City(id: 1, name: "Potenza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Matera", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Policoro", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Melfi", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Pisticci", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Lavello", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Rionero in Vulture", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Lauria", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Bernalda", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Venosa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 3, name: "Calabria", cities: [
        City(id: 1, name: "Catanzaro", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Reggio Calabria", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Cosenza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Lamezia Terme", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Crotone", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Vibo Valentia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Castrovillari", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Acri", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Rossano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Corigliano Calabro", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 4, name: "Campania", cities: [
        City(id: 1, name: "Naples", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Salerno", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Giugliano in Campania", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Torre del Greco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Pozzuoli", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Caserta", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Benevento", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Avellino", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Castellammare di Stabia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Afragola", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 5, name: "Emilia-Romagna", cities: [
        City(id: 1, name: "Bologna", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Parma", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Modena", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Reggio Emilia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Ravenna", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Rimini", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Ferrara", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Forlì", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Piacenza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Cesena", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 6, name: "Friuli-Venezia Giulia", cities: [
        City(id: 1, name: "Trieste", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Udine", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Pordenone", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Gorizia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Monfalcone", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Sacile", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Cordenons", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Codroipo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Azzano Decimo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "San Vito al Tagliamento", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 7, name: "Lazio", cities: [
        City(id: 1, name: "Rome", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Latina", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Guidonia Montecelio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Fiumicino", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Aprilia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Viterbo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Pomezia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Tivoli", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Anzio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Velletri", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 8, name: "Liguria", cities: [
        City(id: 1, name: "Genoa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "La Spezia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Savona", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Sanremo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Imperia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Rapallo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Chiavari", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Ventimiglia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Albenga", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Sarzana", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 9, name: "Lombardy", cities: [
        City(id: 1, name: "Milan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Brescia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Monza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Bergamo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Busto Arsizio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Como", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Varese", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Sesto San Giovanni", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Cinisello Balsamo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Pavia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 10, name: "Marche", cities: [
        City(id: 1, name: "Ancona", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Pesaro", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Fano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Ascoli Piceno", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "San Benedetto del Tronto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Senigallia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Macerata", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Civitanova Marche", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Jesi", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Fermo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 11, name: "Molise", cities: [
        City(id: 1, name: "Campobasso", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Isernia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Termoli", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Venafro", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Bojano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Campomarino", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Larino", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Montenero di Bisaccia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Riccia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Agnone", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 12, name: "Piedmont", cities: [
        City(id: 1, name: "Turin", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Novara", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Alessandria", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Asti", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Moncalieri", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Cuneo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Collegno", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Rivoli", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Vercelli", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Biella", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 13, name: "Apulia", cities: [
        City(id: 1, name: "Bari", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Taranto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Foggia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Andria", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Barletta", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Lecce", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Brindisi", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Altamura", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Molfetta", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Cerignola", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 14, name: "Sardinia", cities: [
        City(id: 1, name: "Cagliari", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Sassari", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Quartu Sant'Elena", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Olbia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Alghero", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Nuoro", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Oristano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Selargius", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Carbonia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Iglesias", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 15, name: "Sicily", cities: [
        City(id: 1, name: "Palermo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Catania", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Messina", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Syracuse", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Marsala", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Gela", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Ragusa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Trapani", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Caltanissetta", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Vittoria", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 16, name: "Tuscany", cities: [
        City(id: 1, name: "Florence", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Prato", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Livorno", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Arezzo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Pistoia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Pisa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Lucca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Grosseto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Massa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Carrara", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 17, name: "Trentino-Alto Adige", cities: [
        City(id: 1, name: "Trento", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Bolzano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Rovereto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Merano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Brixen", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Pergine Valsugana", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Laives", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Arco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Riva del Garda", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Brunico", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 18, name: "Umbria", cities: [
        City(id: 1, name: "Perugia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Terni", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Foligno", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Città di Castello", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Spoleto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Gubbio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Assisi", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Bastia Umbra", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Orvieto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Corciano", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 19, name: "Valle d'Aosta", cities: [
        City(id: 1, name: "Aosta", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Sarre", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Châtillon", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Saint-Vincent", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Quart", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Pont-Saint-Martin", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Saint-Christophe", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Gressan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Courmayeur", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Verrès", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 20, name: "Veneto", cities: [
        City(id: 1, name: "Venice", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Verona", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Padua", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Vicenza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Treviso", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Rovigo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Chioggia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Bassano del Grappa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "San Donà di Piave", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Schio", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
])
