//
//  MexicoCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let mexico = Country(id: 3, name: "Mexico", regions: [
    Region(id: 1, name: "Estado de México", cities: [
        City(id: 1, name: "Ecatepec", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Nezahualcóyotl", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Toluca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Naucalpan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Chimalhuacán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Tlalnepantla", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Cuautitlán Izcalli", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Tecámac", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Ixtapaluca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Atizapán de Zaragoza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 2, name: "Ciudad de México", cities: [
        City(id: 1, name: "Iztapalapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Gustavo A. Madero", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Álvaro Obregón", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Tlalpan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Coyoacán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Cuauhtémoc", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Venustiano Carranza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Xochimilco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Benito Juárez", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Azcapotzalco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 3, name: "Jalisco", cities: [
        City(id: 1, name: "Guadalajara", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Zapopan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Tlaquepaque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Tonalá", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Puerto Vallarta", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Tlajomulco de Zúñiga", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "El Salto", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Lagos de Moreno", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Tepatitlán de Morelos", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Ciudad Guzmán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 4, name: "Veracruz", cities: [
        City(id: 1, name: "Veracruz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Xalapa", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Coatzacoalcos", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Orizaba", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Minatitlán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Poza Rica", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Córdoba", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Boca del Río", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 9, name: "Tuxpan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 10, name: "Papantla", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 5, name: "Puebla", cities: [
        City(id: 1, name: "Puebla", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Tehuacán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "San Martín Texmelucan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Cholula", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Atlixco", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Amozoc", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "Huauchinango", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Teziutlán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 6, name: "Guanajuato", cities: [
        City(id: 1, name: "León", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Irapuato", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Celaya", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Salamanca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Guanajuato", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "Silao", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "San Miguel de Allende", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Valle de Santiago", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 7, name: "Chiapas", cities: [
        City(id: 1, name: "Tuxtla Gutiérrez", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Tapachula", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "San Cristóbal de las Casas", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Comitán de Domínguez", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Palenque", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 8, name: "Nuevo León", cities: [
        City(id: 1, name: "Monterrey", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Guadalupe", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Apodaca", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "San Nicolás de los Garza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Santa Catarina", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 6, name: "General Escobedo", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 7, name: "San Pedro Garza García", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 8, name: "Juárez", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 9, name: "Michoacán", cities: [
        City(id: 1, name: "Morelia", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Uruapan", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "Zamora", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Lázaro Cárdenas", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Apatzingán", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
    Region(id: 10, name: "Oaxaca", cities: [
        City(id: 1, name: "Oaxaca de Juárez", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 2, name: "Juchitán de Zaragoza", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 3, name: "San Juan Bautista Tuxtepec", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 4, name: "Salina Cruz", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
        City(id: 5, name: "Huajuapan de León", legalName: "", coordinates: .init(lat: 0.0, lng: 0.0)),
    ]),
])
