//
//  SpainCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let spain = Country(id: 4, name: "Spain", regions: [
    Region(id: 1, name: "Andalusia", cities: [
        City(id: 1, name: "Seville"),
        City(id: 2, name: "Málaga"),
        City(id: 3, name: "Córdoba"),
        City(id: 4, name: "Granada"),
        City(id: 5, name: "Jerez de la Frontera"),
        City(id: 6, name: "Almería"),
        City(id: 7, name: "Huelva"),
        City(id: 8, name: "Marbella"),
        City(id: 9, name: "Dos Hermanas"),
        City(id: 10, name: "Algeciras"),
    ]),
    Region(id: 2, name: "Aragon", cities: [
        City(id: 1, name: "Zaragoza"),
        City(id: 2, name: "Huesca"),
        City(id: 3, name: "Teruel"),
        City(id: 4, name: "Calatayud"),
        City(id: 5, name: "Ejea de los Caballeros"),
        City(id: 6, name: "Monzón"),
        City(id: 7, name: "Barbastro"),
        City(id: 8, name: "Alcañiz"),
        City(id: 9, name: "Fraga"),
        City(id: 10, name: "Jaca"),
    ]),
    Region(id: 3, name: "Asturias", cities: [
        City(id: 1, name: "Gijón"),
        City(id: 2, name: "Oviedo"),
        City(id: 3, name: "Avilés"),
        City(id: 4, name: "Siero"),
        City(id: 5, name: "Langreo"),
        City(id: 6, name: "Mieres"),
        City(id: 7, name: "Castrillón"),
        City(id: 8, name: "San Martín del Rey Aurelio"),
        City(id: 9, name: "Corvera de Asturias"),
        City(id: 10, name: "Villaviciosa"),
    ]),
    Region(id: 4, name: "Balearic Islands", cities: [
        City(id: 1, name: "Palma"),
        City(id: 2, name: "Calvià"),
        City(id: 3, name: "Ibiza"),
        City(id: 4, name: "Manacor"),
        City(id: 5, name: "Llucmajor"),
        City(id: 6, name: "Marratxí"),
        City(id: 7, name: "Santa Eulària des Riu"),
        City(id: 8, name: "Inca"),
        City(id: 9, name: "Ciutadella de Menorca"),
        City(id: 10, name: "Maó-Mahón"),
    ]),
    Region(id: 5, name: "Canary Islands", cities: [
        City(id: 1, name: "Las Palmas de Gran Canaria"),
        City(id: 2, name: "Santa Cruz de Tenerife"),
        City(id: 3, name: "San Cristóbal de La Laguna"),
        City(id: 4, name: "Telde"),
        City(id: 5, name: "Arona"),
        City(id: 6, name: "Santa Lucía de Tirajana"),
        City(id: 7, name: "Arrecife"),
        City(id: 8, name: "San Bartolomé de Tirajana"),
        City(id: 9, name: "Adeje"),
        City(id: 10, name: "La Orotava"),
    ]),
    Region(id: 6, name: "Cantabria", cities: [
        City(id: 1, name: "Santander"),
        City(id: 2, name: "Torrelavega"),
        City(id: 3, name: "Castro-Urdiales"),
        City(id: 4, name: "Camargo"),
        City(id: 5, name: "Piélagos"),
        City(id: 6, name: "El Astillero"),
        City(id: 7, name: "Laredo"),
        City(id: 8, name: "Santoña"),
        City(id: 9, name: "Los Corrales de Buelna"),
        City(id: 10, name: "Santa Cruz de Bezana"),
    ]),
    Region(id: 7, name: "Castile and León", cities: [
        City(id: 1, name: "Valladolid"),
        City(id: 2, name: "Burgos"),
        City(id: 3, name: "Salamanca"),
        City(id: 4, name: "León"),
        City(id: 5, name: "Zamora"),
        City(id: 6, name: "Palencia"),
        City(id: 7, name: "Ponferrada"),
        City(id: 8, name: "Segovia"),
        City(id: 9, name: "Ávila"),
        City(id: 10, name: "Miranda de Ebro"),
    ]),
    Region(id: 8, name: "Castile-La Mancha", cities: [
        City(id: 1, name: "Albacete"),
        City(id: 2, name: "Talavera de la Reina"),
        City(id: 3, name: "Guadalajara"),
        City(id: 4, name: "Toledo"),
        City(id: 5, name: "Ciudad Real"),
        City(id: 6, name: "Cuenca"),
        City(id: 7, name: "Puertollano"),
        City(id: 8, name: "Tomelloso"),
        City(id: 9, name: "Azuqueca de Henares"),
        City(id: 10, name: "Hellín"),
    ]),
    Region(id: 9, name: "Catalonia", cities: [
        City(id: 1, name: "Barcelona"),
        City(id: 2, name: "L'Hospitalet de Llobregat"),
        City(id: 3, name: "Badalona"),
        City(id: 4, name: "Terrassa"),
        City(id: 5, name: "Sabadell"),
        City(id: 6, name: "Lleida"),
        City(id: 7, name: "Tarragona"),
        City(id: 8, name: "Mataró"),
        City(id: 9, name: "Santa Coloma de Gramenet"),
        City(id: 10, name: "Reus"),
    ]),
    Region(id: 10, name: "Extremadura", cities: [
        City(id: 1, name: "Badajoz"),
        City(id: 2, name: "Cáceres"),
        City(id: 3, name: "Mérida"),
        City(id: 4, name: "Plasencia"),
        City(id: 5, name: "Don Benito"),
        City(id: 6, name: "Almendralejo"),
        City(id: 7, name: "Villanueva de la Serena"),
        City(id: 8, name: "Zafra"),
        City(id: 9, name: "Montijo"),
        City(id: 10, name: "Villafranca de los Barros"),
    ]),
    Region(id: 11, name: "Galicia", cities: [
        City(id: 1, name: "Vigo"),
        City(id: 2, name: "A Coruña"),
        City(id: 3, name: "Ourense"),
        City(id: 4, name: "Lugo"),
        City(id: 5, name: "Santiago de Compostela"),
        City(id: 6, name: "Pontevedra"),
        City(id: 7, name: "Ferrol"),
        City(id: 8, name: "Narón"),
        City(id: 9, name: "Vilagarcía de Arousa"),
        City(id: 10, name: "Oleiros"),
    ]),
    Region(id: 12, name: "Madrid", cities: [
        City(id: 1, name: "Madrid"),
        City(id: 2, name: "Móstoles"),
        City(id: 3, name: "Alcalá de Henares"),
        City(id: 4, name: "Fuenlabrada"),
        City(id: 5, name: "Leganés"),
        City(id: 6, name: "Getafe"),
        City(id: 7, name: "Alcorcón"),
        City(id: 8, name: "Torrejón de Ardoz"),
        City(id: 9, name: "Parla"),
        City(id: 10, name: "Alcobendas"),
    ]),
    Region(id: 13, name: "Murcia", cities: [
        City(id: 1, name: "Murcia"),
        City(id: 2, name: "Cartagena"),
        City(id: 3, name: "Lorca"),
        City(id: 4, name: "Molina de Segura"),
        City(id: 5, name: "Alcantarilla"),
        City(id: 6, name: "Mazarrón"),
        City(id: 7, name: "Cieza"),
        City(id: 8, name: "Águilas"),
        City(id: 9, name: "Yecla"),
        City(id: 10, name: "Torre-Pacheco"),
    ]),
    Region(id: 14, name: "Navarre", cities: [
        City(id: 1, name: "Pamplona"),
        City(id: 2, name: "Tudela"),
        City(id: 3, name: "Barañáin"),
        City(id: 4, name: "Burlada"),
        City(id: 5, name: "Egüés"),
        City(id: 6, name: "Zizur Mayor"),
        City(id: 7, name: "Estella-Lizarra"),
        City(id: 8, name: "Tafalla"),
        City(id: 9, name: "Ansoáin"),
        City(id: 10, name: "Villava"),
    ]),
    Region(id: 15, name: "La Rioja", cities: [
        City(id: 1, name: "Logroño"),
        City(id: 2, name: "Calahorra"),
        City(id: 3, name: "Arnedo"),
        City(id: 4, name: "Haro"),
        City(id: 5, name: "Alfaro"),
        City(id: 6, name: "Nájera"),
        City(id: 7, name: "Lardero"),
        City(id: 8, name: "Villamediana de Iregua"),
        City(id: 9, name: "Santo Domingo de la Calzada"),
        City(id: 10, name: "Autol"),
    ]),
    Region(id: 16, name: "Valencian Community", cities: [
        City(id: 1, name: "Valencia"),
        City(id: 2, name: "Alicante"),
        City(id: 3, name: "Elche"),
        City(id: 4, name: "Castellón de la Plana"),
        City(id: 5, name: "Torrevieja"),
        City(id: 6, name: "Orihuela"),
        City(id: 7, name: "Gandia"),
        City(id: 8, name: "Torrent"),
        City(id: 9, name: "Benidorm"),
        City(id: 10, name: "Sagunto"),
    ]),
    Region(id: 17, name: "Basque Country", cities: [
        City(id: 1, name: "Bilbao"),
        City(id: 2, name: "Vitoria-Gasteiz"),
        City(id: 3, name: "San Sebastián"),
        City(id: 4, name: "Barakaldo"),
        City(id: 5, name: "Getxo"),
        City(id: 6, name: "Portugalete"),
        City(id: 7, name: "Santurtzi"),
        City(id: 8, name: "Basauri"),
        City(id: 9, name: "Errenteria"),
        City(id: 10, name: "Leioa"),
    ]),
    Region(id: 18, name: "Ceuta", cities: [
        City(id: 1, name: "Ceuta"),
    ]),
    Region(id: 19, name: "Melilla", cities: [
        City(id: 1, name: "Melilla"),
    ]),
])
