//
//  SpainCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let spain = Country(id: 4, name: "Spain", regions: [
    Region(id: 1, name: "Andalusia", cities: [
        City(id: 1, name: "Seville", legalName: "Province of Toledo", isCapital: false, coordinates: .init(lat: 39.57488, lng: -4.96387)),
        City(id: 2, name: "Málaga", legalName: "Provincia de Málaga", isCapital: false, coordinates: .init(lat: 36.78107, lng: -4.10266)),
        City(id: 3, name: "Córdoba", legalName: "Province of Córdoba", isCapital: false, coordinates: .init(lat: 37.57996, lng: -4.74935)),
        City(id: 4, name: "Granada", legalName: "Provincia de Granada", isCapital: false, coordinates: .init(lat: 37.00689, lng: -3.98963)),
        City(id: 5, name: "Jerez de la Frontera", legalName: "Provincia de Cádiz", isCapital: false, coordinates: .init(lat: 36.68645, lng: -6.13606)),
        City(id: 6, name: "Almería", legalName: "Almería", isCapital: false, coordinates: .init(lat: 36.88507, lng: -2.4376)),
        City(id: 7, name: "Huelva", legalName: "Provincia de Huelva", isCapital: false, coordinates: .init(lat: 37.26638, lng: -6.94004)),
        City(id: 8, name: "Marbella", legalName: "Provincia de Málaga", isCapital: false, coordinates: .init(lat: 36.51543, lng: -4.88583)),
        City(id: 9, name: "Dos Hermanas", legalName: "Provincia de Sevilla", isCapital: false, coordinates: .init(lat: 37.28287, lng: -5.92088)),
        City(id: 10, name: "Algeciras", legalName: "Provincia de Cádiz", isCapital: false, coordinates: .init(lat: 36.13326, lng: -5.45051)),
    ]),
    Region(id: 2, name: "Aragon", cities: [
        City(id: 1, name: "Zaragoza", legalName: "Provincia de Zaragoza", isCapital: false, coordinates: .init(lat: 41.65606, lng: -0.87734)),
        City(id: 2, name: "Huesca", legalName: "Provincia de Granada", isCapital: false, coordinates: .init(lat: 37.81104, lng: -2.54116)),
        City(id: 3, name: "Teruel", legalName: "Provincia de Madrid", isCapital: false, coordinates: .init(lat: 40.55032, lng: -3.37295)),
        City(id: 4, name: "Calatayud", legalName: "Provincia de Zaragoza", isCapital: false, coordinates: .init(lat: 41.35353, lng: -1.64318)),
        City(id: 5, name: "Ejea de los Caballeros", legalName: "Provincia de Zaragoza", isCapital: false, coordinates: .init(lat: 42.12632, lng: -1.13716)),
        City(id: 6, name: "Monzón", legalName: "Provincia de Palencia", isCapital: false, coordinates: .init(lat: 42.11604, lng: -4.49283)),
        City(id: 7, name: "Barbastro", legalName: "Provincia de Huesca", isCapital: false, coordinates: .init(lat: 42.03565, lng: 0.12686)),
        City(id: 8, name: "Alcañiz", legalName: "Province of Toledo", isCapital: false, coordinates: .init(lat: 39.90315, lng: -5.10588)),
        City(id: 9, name: "Fraga", legalName: "Provincia de Huesca", isCapital: false, coordinates: .init(lat: 41.52294, lng: 0.34894)),
        City(id: 10, name: "Jaca", legalName: "Almería", isCapital: false, coordinates: .init(lat: 37.1402, lng: -1.85102)),
    ]),
    Region(id: 3, name: "Asturias", cities: [
        City(id: 1, name: "Gijón", legalName: "Province of Asturias", isCapital: false, coordinates: .init(lat: 43.53573, lng: -5.66152)),
        City(id: 2, name: "Oviedo", legalName: "Province of Asturias", isCapital: false, coordinates: .init(lat: 43.36029, lng: -5.84476)),
        City(id: 3, name: "Avilés", legalName: "Province of Asturias", isCapital: false, coordinates: .init(lat: 43.55473, lng: -5.92483)),
        City(id: 4, name: "Siero", legalName: "Province of Asturias", isCapital: false, coordinates: .init(lat: 43.39228, lng: -5.66335)),
        City(id: 5, name: "Langreo", legalName: "Provincia de Valladolid", isCapital: false, coordinates: .init(lat: 41.56986, lng: -4.19866)),
        City(id: 6, name: "Mieres", legalName: "Province of Asturias", isCapital: false, coordinates: .init(lat: 43.25, lng: -5.76667)),
        City(id: 7, name: "Castrillón", legalName: "Province of Asturias", isCapital: false, coordinates: .init(lat: 43.54793, lng: -5.99381)),
        City(id: 8, name: "San Martín del Rey Aurelio", legalName: "", isCapital: false, coordinates: .init(lat: 0, lng: 0)),
        City(id: 9, name: "Corvera de Asturias", legalName: "Province of Asturias", isCapital: false, coordinates: .init(lat: 43.53554, lng: -5.88893)),
        City(id: 10, name: "Villaviciosa", legalName: "Province of Córdoba", isCapital: false, coordinates: .init(lat: 38.08333, lng: -5.01667)),
    ]),
    Region(id: 4, name: "Balearic Islands", cities: [
        City(id: 1, name: "Palma", legalName: "Provincia de Santa Cruz de Tenerife", isCapital: false, coordinates: .init(lat: 28.49236, lng: -17.84529)),
        City(id: 2, name: "Calvià", legalName: "Illes Balears", isCapital: false, coordinates: .init(lat: 39.5657, lng: 2.50621)),
        City(id: 3, name: "Ibiza", legalName: "Illes Balears", isCapital: false, coordinates: .init(lat: 38.90883, lng: 1.43296)),
        City(id: 4, name: "Manacor", legalName: "Illes Balears", isCapital: false, coordinates: .init(lat: 39.56964, lng: 3.20955)),
        City(id: 5, name: "Llucmajor", legalName: "Illes Balears", isCapital: false, coordinates: .init(lat: 39.49093, lng: 2.89108)),
        City(id: 6, name: "Marratxí", legalName: "Illes Balears", isCapital: false, coordinates: .init(lat: 39.62142, lng: 2.7253)),
        City(id: 7, name: "Santa Eulària des Riu", legalName: "Illes Balears", isCapital: false, coordinates: .init(lat: 38.98457, lng: 1.53409)),
        City(id: 8, name: "Inca", legalName: "Illes Balears", isCapital: false, coordinates: .init(lat: 39.7211, lng: 2.91093)),
        City(id: 9, name: "Ciutadella de Menorca", legalName: "", isCapital: false, coordinates: .init(lat: 0, lng: 0)),
        City(id: 10, name: "Maó-Mahón", legalName: "", isCapital: false, coordinates: .init(lat: 0, lng: 0)),
    ]),
    Region(id: 5, name: "Canary Islands", cities: [
        City(id: 1, name: "Las Palmas de Gran Canaria", legalName: "Provincia de Las Palmas", isCapital: false, coordinates: .init(lat: 28.09973, lng: -15.41343)),
        City(id: 2, name: "Santa Cruz de Tenerife", legalName: "Provincia de Santa Cruz de Tenerife", isCapital: false, coordinates: .init(lat: 28.46824, lng: -16.25462)),
        City(id: 3, name: "San Cristóbal de La Laguna", legalName: "", isCapital: false, coordinates: .init(lat: 0, lng: 0)),
        City(id: 4, name: "Telde", legalName: "Provincia de Las Palmas", isCapital: false, coordinates: .init(lat: 27.99243, lng: -15.41915)),
        City(id: 5, name: "Arona", legalName: "Provincia de Santa Cruz de Tenerife", isCapital: false, coordinates: .init(lat: 28.09962, lng: -16.68102)),
        City(id: 6, name: "Santa Lucía de Tirajana", legalName: "", isCapital: false, coordinates: .init(lat: 0, lng: 0)),
        City(id: 7, name: "Arrecife", legalName: "Provincia de Las Palmas", isCapital: false, coordinates: .init(lat: 28.96302, lng: -13.54769)),
        City(id: 8, name: "San Bartolomé de Tirajana", legalName: "Provincia de Las Palmas", isCapital: false, coordinates: .init(lat: 27.92481, lng: -15.57329)),
        City(id: 9, name: "Adeje", legalName: "Provincia de Santa Cruz de Tenerife", isCapital: false, coordinates: .init(lat: 28.12271, lng: -16.726)),
        City(id: 10, name: "La Orotava", legalName: "Provincia de Santa Cruz de Tenerife", isCapital: false, coordinates: .init(lat: 28.39076, lng: -16.52309)),
    ]),
    Region(id: 6, name: "Cantabria", cities: [
        City(id: 1, name: "Santander", legalName: "Provincia de Cantabria", isCapital: false, coordinates: .init(lat: 43.46472, lng: -3.80444)),
        City(id: 2, name: "Torrelavega", legalName: "Provincia de Cantabria", isCapital: false, coordinates: .init(lat: 43.34943, lng: -4.04785)),
        City(id: 3, name: "Castro-Urdiales", legalName: "Provincia de Cantabria", isCapital: false, coordinates: .init(lat: 43.38285, lng: -3.22043)),
        City(id: 4, name: "Camargo", legalName: "Provincia de Cantabria", isCapital: false, coordinates: .init(lat: 43.40744, lng: -3.88498)),
        City(id: 5, name: "Piélagos", legalName: "Provincia de Madrid", isCapital: false, coordinates: .init(lat: 40.75842, lng: -3.46163)),
        City(id: 6, name: "El Astillero", legalName: "Provincia de Cantabria", isCapital: false, coordinates: .init(lat: 43.40094, lng: -3.82051)),
        City(id: 7, name: "Laredo", legalName: "Provincia de Cantabria", isCapital: false, coordinates: .init(lat: 43.4098, lng: -3.41613)),
        City(id: 8, name: "Santoña", legalName: "Provincia de Cantabria", isCapital: false, coordinates: .init(lat: 43.44386, lng: -3.45757)),
        City(id: 9, name: "Los Corrales de Buelna", legalName: "Provincia de Cantabria", isCapital: false, coordinates: .init(lat: 43.26358, lng: -4.07262)),
        City(id: 10, name: "Santa Cruz de Bezana", legalName: "Provincia de Cantabria", isCapital: false, coordinates: .init(lat: 43.4437, lng: -3.90324)),
    ]),
    Region(id: 7, name: "Castile and León", cities: [
        City(id: 1, name: "Valladolid", legalName: "Provincia de Valladolid", isCapital: false, coordinates: .init(lat: 41.65518, lng: -4.72372)),
        City(id: 2, name: "Burgos", legalName: "Provincia de Burgos", isCapital: false, coordinates: .init(lat: 42.25838, lng: -3.69707)),
        City(id: 3, name: "Salamanca", legalName: "Provincia de Salamanca", isCapital: false, coordinates: .init(lat: 40.95978, lng: -5.74349)),
        City(id: 4, name: "León", legalName: "Provincia de Huelva", isCapital: false, coordinates: .init(lat: 37.37628, lng: -6.96895)),
        City(id: 5, name: "Zamora", legalName: "Provincia de Zamora", isCapital: false, coordinates: .init(lat: 41.50633, lng: -5.74456)),
        City(id: 6, name: "Palencia", legalName: "Province of Córdoba", isCapital: false, coordinates: .init(lat: 37.24851, lng: -4.58261)),
        City(id: 7, name: "Ponferrada", legalName: "Provincia de León", isCapital: false, coordinates: .init(lat: 42.54664, lng: -6.59619)),
        City(id: 8, name: "Segovia", legalName: "Provincia de Segovia", isCapital: false, coordinates: .init(lat: 40.94808, lng: -4.11839)),
        City(id: 9, name: "Ávila", legalName: "Provincia de Ávila", isCapital: false, coordinates: .init(lat: 40.3571, lng: -5.52365)),
        City(id: 10, name: "Miranda de Ebro", legalName: "Provincia de Burgos", isCapital: false, coordinates: .init(lat: 42.6865, lng: -2.94695)),
    ]),
    Region(id: 8, name: "Castile-La Mancha", cities: [
        City(id: 1, name: "Albacete", legalName: "Provincia de Albacete", isCapital: false, coordinates: .init(lat: 38.99424, lng: -1.85643)),
        City(id: 2, name: "Talavera de la Reina", legalName: "Province of Toledo", isCapital: false, coordinates: .init(lat: 39.96348, lng: -4.83076)),
        City(id: 3, name: "Guadalajara", legalName: "Provincia de Guadalajara", isCapital: false, coordinates: .init(lat: 40.49533, lng: -3.1814)),
        City(id: 4, name: "Toledo", legalName: "Province of Toledo", isCapital: false, coordinates: .init(lat: 39.79635, lng: -3.99254)),
        City(id: 5, name: "Ciudad Real", legalName: "Provincia de Ciudad Real", isCapital: false, coordinates: .init(lat: 38.98626, lng: -3.92907)),
        City(id: 6, name: "Cuenca", legalName: "Provincia de Cuenca", isCapital: false, coordinates: .init(lat: 40.06667, lng: -2.13333)),
        City(id: 7, name: "Puertollano", legalName: "Provincia de Ciudad Real", isCapital: false, coordinates: .init(lat: 38.68712, lng: -4.10734)),
        City(id: 8, name: "Tomelloso", legalName: "Provincia de Ciudad Real", isCapital: false, coordinates: .init(lat: 39.15759, lng: -3.02156)),
        City(id: 9, name: "Azuqueca de Henares", legalName: "Provincia de Guadalajara", isCapital: false, coordinates: .init(lat: 40.56566, lng: -3.26753)),
        City(id: 10, name: "Hellín", legalName: "Provincia de Albacete", isCapital: false, coordinates: .init(lat: 38.5106, lng: -1.70096)),
    ]),
    Region(id: 9, name: "Catalonia", cities: [
        City(id: 1, name: "Barcelona", legalName: "Província de Barcelona", isCapital: false, coordinates: .init(lat: 41.38879, lng: 2.15899)),
        City(id: 2, name: "L'Hospitalet de Llobregat", legalName: "Província de Barcelona", isCapital: false, coordinates: .init(lat: 41.35967, lng: 2.10028)),
        City(id: 3, name: "Badalona", legalName: "Província de Barcelona", isCapital: false, coordinates: .init(lat: 41.45004, lng: 2.24741)),
        City(id: 4, name: "Terrassa", legalName: "Província de Barcelona", isCapital: false, coordinates: .init(lat: 41.56667, lng: 2.01667)),
        City(id: 5, name: "Sabadell", legalName: "Província de Barcelona", isCapital: false, coordinates: .init(lat: 41.54329, lng: 2.10942)),
        City(id: 6, name: "Lleida", legalName: "Província de Lleida", isCapital: false, coordinates: .init(lat: 41.61674, lng: 0.62218)),
        City(id: 7, name: "Tarragona", legalName: "Província de Tarragona", isCapital: false, coordinates: .init(lat: 41.11905, lng: 1.24544)),
        City(id: 8, name: "Mataró", legalName: "Província de Barcelona", isCapital: false, coordinates: .init(lat: 41.54211, lng: 2.4445)),
        City(id: 9, name: "Santa Coloma de Gramenet", legalName: "Província de Barcelona", isCapital: false, coordinates: .init(lat: 41.45152, lng: 2.2081)),
        City(id: 10, name: "Reus", legalName: "Província de Tarragona", isCapital: false, coordinates: .init(lat: 41.15612, lng: 1.10687)),
    ]),
    Region(id: 10, name: "Extremadura", cities: [
        City(id: 1, name: "Badajoz", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.87789, lng: -6.97061)),
        City(id: 2, name: "Cáceres", legalName: "Provincia de Cáceres", isCapital: false, coordinates: .init(lat: 39.44664, lng: -6.5076)),
        City(id: 3, name: "Mérida", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.91611, lng: -6.34366)),
        City(id: 4, name: "Plasencia", legalName: "Provincia de Cáceres", isCapital: false, coordinates: .init(lat: 40.03116, lng: -6.08845)),
        City(id: 5, name: "Don Benito", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.95627, lng: -5.86162)),
        City(id: 6, name: "Almendralejo", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.68316, lng: -6.40747)),
        City(id: 7, name: "Villanueva de la Serena", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.97655, lng: -5.7974)),
        City(id: 8, name: "Zafra", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.42539, lng: -6.41734)),
        City(id: 9, name: "Montijo", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.90839, lng: -6.61785)),
        City(id: 10, name: "Villafranca de los Barros", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.56144, lng: -6.3381)),
    ]),
    Region(id: 11, name: "Galicia", cities: [
        City(id: 1, name: "Vigo", legalName: "Provincia de Pontevedra", isCapital: false, coordinates: .init(lat: 42.23282, lng: -8.72264)),
        City(id: 2, name: "A Coruña", legalName: "Provincia da Coruña", isCapital: false, coordinates: .init(lat: 43.37135, lng: -8.396)),
        City(id: 3, name: "Ourense", legalName: "Provincia de Ourense", isCapital: false, coordinates: .init(lat: 42.33669, lng: -7.86407)),
        City(id: 4, name: "Lugo", legalName: "Provincia de Lugo", isCapital: false, coordinates: .init(lat: 43.00992, lng: -7.55602)),
        City(id: 5, name: "Santiago de Compostela", legalName: "Provincia da Coruña", isCapital: false, coordinates: .init(lat: 42.88052, lng: -8.54569)),
        City(id: 6, name: "Pontevedra", legalName: "Provincia de Pontevedra", isCapital: false, coordinates: .init(lat: 42.431, lng: -8.64435)),
        City(id: 7, name: "Ferrol", legalName: "Provincia da Coruña", isCapital: false, coordinates: .init(lat: 43.48451, lng: -8.23293)),
        City(id: 8, name: "Narón", legalName: "Provincia da Coruña", isCapital: false, coordinates: .init(lat: 43.50175, lng: -8.19082)),
        City(id: 9, name: "Vilagarcía de Arousa", legalName: "Provincia de Pontevedra", isCapital: false, coordinates: .init(lat: 42.59631, lng: -8.76426)),
        City(id: 10, name: "Oleiros", legalName: "Provincia da Coruña", isCapital: false, coordinates: .init(lat: 43.33333, lng: -8.31667)),
    ]),
    Region(id: 12, name: "Madrid", cities: [
        City(id: 1, name: "Madrid", legalName: "Province of Toledo", isCapital: false, coordinates: .init(lat: 39.46823, lng: -3.53196)),
        City(id: 2, name: "Móstoles", legalName: "Provincia de Madrid", isCapital: false, coordinates: .init(lat: 40.32234, lng: -3.86496)),
        City(id: 3, name: "Alcalá de Henares", legalName: "Provincia de Madrid", isCapital: false, coordinates: .init(lat: 40.48205, lng: -3.35996)),
        City(id: 4, name: "Fuenlabrada", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 39.13288, lng: -4.93513)),
        City(id: 5, name: "Leganés", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.67059, lng: -6.98036)),
        City(id: 6, name: "Getafe", legalName: "Provincia de Madrid", isCapital: false, coordinates: .init(lat: 40.30571, lng: -3.73295)),
        City(id: 7, name: "Alcorcón", legalName: "Provincia de Madrid", isCapital: false, coordinates: .init(lat: 40.34582, lng: -3.82487)),
        City(id: 8, name: "Torrejón de Ardoz", legalName: "Provincia de Madrid", isCapital: false, coordinates: .init(lat: 40.45535, lng: -3.46973)),
        City(id: 9, name: "Parla", legalName: "Provincia de Madrid", isCapital: false, coordinates: .init(lat: 40.23604, lng: -3.76752)),
        City(id: 10, name: "Alcobendas", legalName: "Provincia de Madrid", isCapital: false, coordinates: .init(lat: 40.54746, lng: -3.64197)),
    ]),
    Region(id: 13, name: "Murcia", cities: [
        City(id: 1, name: "Murcia", legalName: "", isCapital: false, coordinates: .init(lat: 37.98704, lng: -1.13004)),
        City(id: 2, name: "Cartagena", legalName: "Murcia", isCapital: false, coordinates: .init(lat: 37.60197, lng: -0.98397)),
        City(id: 3, name: "Lorca", legalName: "Murcia", isCapital: false, coordinates: .init(lat: 37.67119, lng: -1.7017)),
        City(id: 4, name: "Molina de Segura", legalName: "Murcia", isCapital: false, coordinates: .init(lat: 38.05456, lng: -1.20763)),
        City(id: 5, name: "Alcantarilla", legalName: "Murcia", isCapital: false, coordinates: .init(lat: 37.96939, lng: -1.21714)),
        City(id: 6, name: "Mazarrón", legalName: "Murcia", isCapital: false, coordinates: .init(lat: 37.5992, lng: -1.31493)),
        City(id: 7, name: "Cieza", legalName: "Murcia", isCapital: false, coordinates: .init(lat: 38.23998, lng: -1.41987)),
        City(id: 8, name: "Águilas", legalName: "Murcia", isCapital: false, coordinates: .init(lat: 37.4063, lng: -1.58289)),
        City(id: 9, name: "Yecla", legalName: "Murcia", isCapital: false, coordinates: .init(lat: 38.61365, lng: -1.11468)),
        City(id: 10, name: "Torre-Pacheco", legalName: "Murcia", isCapital: false, coordinates: .init(lat: 37.74293, lng: -0.95396)),
    ]),
    Region(id: 14, name: "Navarre", cities: [
        City(id: 1, name: "Pamplona", legalName: "Provincia de Navarra", isCapital: false, coordinates: .init(lat: 42.81687, lng: -1.64323)),
        City(id: 2, name: "Tudela", legalName: "Provincia de Valladolid", isCapital: false, coordinates: .init(lat: 41.5845, lng: -4.58093)),
        City(id: 3, name: "Barañáin", legalName: "Provincia de Navarra", isCapital: false, coordinates: .init(lat: 42.80567, lng: -1.67731)),
        City(id: 4, name: "Burlada", legalName: "Provincia de Navarra", isCapital: false, coordinates: .init(lat: 42.82562, lng: -1.61671)),
        City(id: 5, name: "Egüés", legalName: "Provincia de Santa Cruz de Tenerife", isCapital: false, coordinates: .init(lat: 28.52236, lng: -16.34074)),
        City(id: 6, name: "Zizur Mayor", legalName: "Provincia de Navarra", isCapital: false, coordinates: .init(lat: 42.78795, lng: -1.69065)),
        City(id: 7, name: "Estella-Lizarra", legalName: "Provincia de Navarra", isCapital: false, coordinates: .init(lat: 42.67182, lng: -2.03226)),
        City(id: 8, name: "Tafalla", legalName: "Provincia de Navarra", isCapital: false, coordinates: .init(lat: 42.52687, lng: -1.67446)),
        City(id: 9, name: "Ansoáin", legalName: "Gipuzkoa", isCapital: false, coordinates: .init(lat: 43.21658, lng: -2.0253)),
        City(id: 10, name: "Villava", legalName: "Provincia de Albacete", isCapital: false, coordinates: .init(lat: 39.12646, lng: -1.45712)),
    ]),
    Region(id: 15, name: "La Rioja", cities: [
        City(id: 1, name: "Logroño", legalName: "Provincia de La Rioja", isCapital: false, coordinates: .init(lat: 42.46667, lng: -2.45)),
        City(id: 2, name: "Calahorra", legalName: "Provincia de Palencia", isCapital: false, coordinates: .init(lat: 42.57409, lng: -4.38485)),
        City(id: 3, name: "Arnedo", legalName: "Provincia de La Rioja", isCapital: false, coordinates: .init(lat: 42.228, lng: -2.10083)),
        City(id: 4, name: "Haro", legalName: "Provincia de Cuenca", isCapital: false, coordinates: .init(lat: 39.33355, lng: -2.27273)),
        City(id: 5, name: "Alfaro", legalName: "Provincia de La Rioja", isCapital: false, coordinates: .init(lat: 42.18032, lng: -1.75016)),
        City(id: 6, name: "Nájera", legalName: "Provincia de La Rioja", isCapital: false, coordinates: .init(lat: 42.41822, lng: -2.72865)),
        City(id: 7, name: "Lardero", legalName: "Provincia de La Rioja", isCapital: false, coordinates: .init(lat: 42.42686, lng: -2.46153)),
        City(id: 8, name: "Villamediana de Iregua", legalName: "Provincia de La Rioja", isCapital: false, coordinates: .init(lat: 42.42658, lng: -2.41943)),
        City(id: 9, name: "Santo Domingo de la Calzada", legalName: "Provincia de La Rioja", isCapital: false, coordinates: .init(lat: 42.44015, lng: -2.95365)),
        City(id: 10, name: "Autol", legalName: "Provincia de La Rioja", isCapital: false, coordinates: .init(lat: 42.21661, lng: -2.00525)),
    ]),
    Region(id: 16, name: "Valencian Community", cities: [
        City(id: 1, name: "Valencia", legalName: "Provincia de Badajoz", isCapital: false, coordinates: .init(lat: 38.24243, lng: -7.11965)),
        City(id: 2, name: "Alicante", legalName: "Provincia de Alicante", isCapital: false, coordinates: .init(lat: 38.34517, lng: -0.48149)),
        City(id: 3, name: "Elche", legalName: "Provincia de Albacete", isCapital: false, coordinates: .init(lat: 38.45123, lng: -2.0476)),
        City(id: 4, name: "Castellón de la Plana", legalName: "Província de Castelló", isCapital: false, coordinates: .init(lat: 39.98567, lng: -0.04935)),
        City(id: 5, name: "Torrevieja", legalName: "Provincia de Alicante", isCapital: false, coordinates: .init(lat: 37.97872, lng: -0.68222)),
        City(id: 6, name: "Orihuela", legalName: "Provincia de Alicante", isCapital: false, coordinates: .init(lat: 38.08483, lng: -0.94401)),
        City(id: 7, name: "Gandia", legalName: "Província de València", isCapital: false, coordinates: .init(lat: 38.92672, lng: -0.22028)),
        City(id: 8, name: "Torrent", legalName: "Província de València", isCapital: false, coordinates: .init(lat: 39.43705, lng: -0.46546)),
        City(id: 9, name: "Benidorm", legalName: "Provincia de Alicante", isCapital: false, coordinates: .init(lat: 38.53816, lng: -0.13098)),
        City(id: 10, name: "Sagunto", legalName: "Província de València", isCapital: false, coordinates: .init(lat: 39.68333, lng: -0.26667)),
    ]),
    Region(id: 17, name: "Basque Country", cities: [
        City(id: 1, name: "Bilbao", legalName: "Bizkaia", isCapital: false, coordinates: .init(lat: 43.26271, lng: -2.92528)),
        City(id: 2, name: "Vitoria-Gasteiz", legalName: "", isCapital: false, coordinates: .init(lat: 0, lng: 0)),
        City(id: 3, name: "San Sebastián", legalName: "Provincia de Santa Cruz de Tenerife", isCapital: false, coordinates: .init(lat: 28.09163, lng: -17.11331)),
        City(id: 4, name: "Barakaldo", legalName: "Bizkaia", isCapital: false, coordinates: .init(lat: 43.29639, lng: -2.98813)),
        City(id: 5, name: "Getxo", legalName: "Bizkaia", isCapital: false, coordinates: .init(lat: 43.35689, lng: -3.01146)),
        City(id: 6, name: "Portugalete", legalName: "Bizkaia", isCapital: false, coordinates: .init(lat: 43.32099, lng: -3.02064)),
        City(id: 7, name: "Santurtzi", legalName: "Bizkaia", isCapital: false, coordinates: .init(lat: 43.32842, lng: -3.03248)),
        City(id: 8, name: "Basauri", legalName: "Bizkaia", isCapital: false, coordinates: .init(lat: 43.2397, lng: -2.8858)),
        City(id: 9, name: "Errenteria", legalName: "Gipuzkoa", isCapital: false, coordinates: .init(lat: 43.31195, lng: -1.90234)),
        City(id: 10, name: "Leioa", legalName: "Bizkaia", isCapital: false, coordinates: .init(lat: 43.32686, lng: -2.98884)),
    ]),
    Region(id: 18, name: "Ceuta", cities: [
        City(id: 1, name: "Ceuta", legalName: "", isCapital: false, coordinates: .init(lat: 35.88919, lng: -5.32042)),
    ]),
    Region(id: 19, name: "Melilla", cities: [
        City(id: 1, name: "Melilla", legalName: "", isCapital: false, coordinates: .init(lat: 35.29369, lng: -2.93833)),
    ]),
])
