//
//  UnitedStatesCatalog.swift
//  Community Issue Reporter
//
//  Created by Francisco Hernandez on 24/3/26.
//

import Foundation

let unitedStates = Country(id: 2, name: "United States", regions: [
    Region(id: 1, name: "California", cities: [
        City(id: 1, name: "Los Angeles"),
        City(id: 2, name: "San Diego"),
        City(id: 3, name: "San Jose"),
        City(id: 4, name: "San Francisco"),
        City(id: 5, name: "Fresno"),
        City(id: 6, name: "Sacramento"),
        City(id: 7, name: "Long Beach"),
        City(id: 8, name: "Oakland"),
        City(id: 9, name: "Bakersfield"),
        City(id: 10, name: "Anaheim"),
    ]),
    Region(id: 2, name: "Texas", cities: [
        City(id: 1, name: "Houston"),
        City(id: 2, name: "San Antonio"),
        City(id: 3, name: "Dallas"),
        City(id: 4, name: "Austin"),
        City(id: 5, name: "Fort Worth"),
        City(id: 6, name: "El Paso"),
        City(id: 7, name: "Arlington"),
        City(id: 8, name: "Corpus Christi"),
        City(id: 9, name: "Plano"),
        City(id: 10, name: "Laredo"),
    ]),
    Region(id: 3, name: "Florida", cities: [
        City(id: 1, name: "Jacksonville"),
        City(id: 2, name: "Miami"),
        City(id: 3, name: "Tampa"),
        City(id: 4, name: "Orlando"),
        City(id: 5, name: "St. Petersburg"),
        City(id: 6, name: "Hialeah"),
        City(id: 7, name: "Tallahassee"),
        City(id: 8, name: "Fort Lauderdale"),
        City(id: 9, name: "Port St. Lucie"),
        City(id: 10, name: "Cape Coral"),
    ]),
    Region(id: 4, name: "New York", cities: [
        City(id: 1, name: "New York City"),
        City(id: 2, name: "Buffalo"),
        City(id: 3, name: "Rochester"),
        City(id: 4, name: "Yonkers"),
        City(id: 5, name: "Syracuse"),
        City(id: 6, name: "Albany"),
        City(id: 7, name: "New Rochelle"),
        City(id: 8, name: "Mount Vernon"),
        City(id: 9, name: "Schenectady"),
        City(id: 10, name: "Utica"),
    ]),
    Region(id: 5, name: "Pennsylvania", cities: [
        City(id: 1, name: "Philadelphia"),
        City(id: 2, name: "Pittsburgh"),
        City(id: 3, name: "Allentown"),
        City(id: 4, name: "Reading"),
        City(id: 5, name: "Erie"),
        City(id: 6, name: "Upper Darby"),
        City(id: 7, name: "Scranton"),
        City(id: 8, name: "Lower Merion"),
        City(id: 9, name: "Bensalem"),
        City(id: 10, name: "Abington"),
    ]),
    Region(id: 6, name: "Illinois", cities: [
        City(id: 1, name: "Chicago"),
        City(id: 2, name: "Aurora"),
        City(id: 3, name: "Joliet"),
        City(id: 4, name: "Naperville"),
        City(id: 5, name: "Rockford"),
        City(id: 6, name: "Springfield"),
        City(id: 7, name: "Elgin"),
        City(id: 8, name: "Peoria"),
        City(id: 9, name: "Champaign"),
        City(id: 10, name: "Waukegan"),
    ]),
    Region(id: 7, name: "Ohio", cities: [
        City(id: 1, name: "Columbus"),
        City(id: 2, name: "Cleveland"),
        City(id: 3, name: "Cincinnati"),
        City(id: 4, name: "Toledo"),
        City(id: 5, name: "Akron"),
        City(id: 6, name: "Dayton"),
        City(id: 7, name: "Parma"),
        City(id: 8, name: "Canton"),
        City(id: 9, name: "Youngstown"),
        City(id: 10, name: "Lorain"),
    ]),
    Region(id: 8, name: "Georgia", cities: [
        City(id: 1, name: "Atlanta"),
        City(id: 2, name: "Augusta"),
        City(id: 3, name: "Columbus"),
        City(id: 4, name: "Macon"),
        City(id: 5, name: "Savannah"),
        City(id: 6, name: "Athens"),
        City(id: 7, name: "Sandy Springs"),
        City(id: 8, name: "South Fulton"),
        City(id: 9, name: "Roswell"),
        City(id: 10, name: "Johns Creek"),
    ]),
    Region(id: 9, name: "North Carolina", cities: [
        City(id: 1, name: "Charlotte"),
        City(id: 2, name: "Raleigh"),
        City(id: 3, name: "Greensboro"),
        City(id: 4, name: "Durham"),
        City(id: 5, name: "Winston-Salem"),
        City(id: 6, name: "Fayetteville"),
        City(id: 7, name: "Cary"),
        City(id: 8, name: "Wilmington"),
        City(id: 9, name: "High Point"),
        City(id: 10, name: "Concord"),
    ]),
    Region(id: 10, name: "Michigan", cities: [
        City(id: 1, name: "Detroit"),
        City(id: 2, name: "Grand Rapids"),
        City(id: 3, name: "Warren"),
        City(id: 4, name: "Sterling Heights"),
        City(id: 5, name: "Ann Arbor"),
        City(id: 6, name: "Lansing"),
        City(id: 7, name: "Clinton"),
        City(id: 8, name: "Flint"),
        City(id: 9, name: "Dearborn"),
        City(id: 10, name: "Livonia"),
    ]),
])
